### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
  commentId: T:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
  id: MetricDimensionNames.TelemetryContext.Device
  parent: Microsoft.ApplicationInsights
  children:
  - Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.Id
  - Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.Language
  - Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.Model
  - Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.NetworkType
  - Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.OemName
  - Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.OperatingSystem
  - Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.ScreenResolution
  - Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.Type
  langs:
  - csharp
  - vb
  name: MetricDimensionNames.TelemetryContext.Device
  nameWithType: MetricDimensionNames.TelemetryContext.Device
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
  type: Class
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  syntax:
    content: public static class MetricDimensionNames.TelemetryContext.Device
    content.vb: Public Module MetricDimensionNames.TelemetryContext.Device
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.Id
  commentId: F:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.Id
  id: Id
  parent: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: MetricDimensionNames.TelemetryContext.Device.Id
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.Id
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  syntax:
    content: public const string Id = "TelemetryContext.Device.Id"
    return:
      type: System.String
    content.vb: Public Const Id As String = "TelemetryContext.Device.Id"
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.Language
  commentId: F:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.Language
  id: Language
  parent: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
  langs:
  - csharp
  - vb
  name: Language
  nameWithType: MetricDimensionNames.TelemetryContext.Device.Language
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.Language
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  syntax:
    content: public const string Language = "TelemetryContext.Device.Language"
    return:
      type: System.String
    content.vb: Public Const Language As String = "TelemetryContext.Device.Language"
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.Model
  commentId: F:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.Model
  id: Model
  parent: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
  langs:
  - csharp
  - vb
  name: Model
  nameWithType: MetricDimensionNames.TelemetryContext.Device.Model
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.Model
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  syntax:
    content: public const string Model = "TelemetryContext.Device.Model"
    return:
      type: System.String
    content.vb: Public Const Model As String = "TelemetryContext.Device.Model"
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.NetworkType
  commentId: F:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.NetworkType
  id: NetworkType
  parent: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
  langs:
  - csharp
  - vb
  name: NetworkType
  nameWithType: MetricDimensionNames.TelemetryContext.Device.NetworkType
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.NetworkType
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  syntax:
    content: public const string NetworkType = "TelemetryContext.Device.NetworkType"
    return:
      type: System.String
    content.vb: Public Const NetworkType As String = "TelemetryContext.Device.NetworkType"
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.OemName
  commentId: F:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.OemName
  id: OemName
  parent: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
  langs:
  - csharp
  - vb
  name: OemName
  nameWithType: MetricDimensionNames.TelemetryContext.Device.OemName
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.OemName
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  syntax:
    content: public const string OemName = "TelemetryContext.Device.OemName"
    return:
      type: System.String
    content.vb: Public Const OemName As String = "TelemetryContext.Device.OemName"
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.OperatingSystem
  commentId: F:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.OperatingSystem
  id: OperatingSystem
  parent: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
  langs:
  - csharp
  - vb
  name: OperatingSystem
  nameWithType: MetricDimensionNames.TelemetryContext.Device.OperatingSystem
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.OperatingSystem
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  syntax:
    content: public const string OperatingSystem = "TelemetryContext.Device.OperatingSystem"
    return:
      type: System.String
    content.vb: Public Const OperatingSystem As String = "TelemetryContext.Device.OperatingSystem"
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.ScreenResolution
  commentId: F:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.ScreenResolution
  id: ScreenResolution
  parent: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
  langs:
  - csharp
  - vb
  name: ScreenResolution
  nameWithType: MetricDimensionNames.TelemetryContext.Device.ScreenResolution
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.ScreenResolution
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  syntax:
    content: public const string ScreenResolution = "TelemetryContext.Device.ScreenResolution"
    return:
      type: System.String
    content.vb: Public Const ScreenResolution As String = "TelemetryContext.Device.ScreenResolution"
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.Type
  commentId: F:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.Type
  id: Type
  parent: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: MetricDimensionNames.TelemetryContext.Device.Type
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.Type
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  syntax:
    content: public const string Type = "TelemetryContext.Device.Type"
    return:
      type: System.String
    content.vb: Public Const Type As String = "TelemetryContext.Device.Type"
references:
- uid: Microsoft.ApplicationInsights
  commentId: N:Microsoft.ApplicationInsights
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights
  nameWithType: Microsoft.ApplicationInsights
  fullName: Microsoft.ApplicationInsights
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
