### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Extensibility
  id: Microsoft.ApplicationInsights.Extensibility
  children:
  - Microsoft.ApplicationInsights.Extensibility.AutocollectedMetricsExtractor
  - Microsoft.ApplicationInsights.Extensibility.IApplicationIdProvider
  - Microsoft.ApplicationInsights.Extensibility.IExtension
  - Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
  - Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter
  - Microsoft.ApplicationInsights.Extensibility.ISerializationWriter
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryModule
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor
  - Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer
  - Microsoft.ApplicationInsights.Extensibility.SdkInternalOperationsMonitor
  - Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer
  - Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
  - Microsoft.ApplicationInsights.Extensibility.TelemetrySink
  langs:
  - csharp
  - vb
  name: Microsoft.ApplicationInsights.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
  type: Namespace
  assemblies:
  - Microsoft.ApplicationInsights
references:
- uid: Microsoft.ApplicationInsights.Extensibility.IApplicationIdProvider
  commentId: T:Microsoft.ApplicationInsights.Extensibility.IApplicationIdProvider
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.IApplicationIdProvider.html
  name: IApplicationIdProvider
  nameWithType: IApplicationIdProvider
  fullName: Microsoft.ApplicationInsights.Extensibility.IApplicationIdProvider
- uid: Microsoft.ApplicationInsights.Extensibility.IExtension
  commentId: T:Microsoft.ApplicationInsights.Extensibility.IExtension
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.IExtension.html
  name: IExtension
  nameWithType: IExtension
  fullName: Microsoft.ApplicationInsights.Extensibility.IExtension
- uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
  commentId: T:Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.IOperationHolder-1.html
  name: IOperationHolder<T>
  nameWithType: IOperationHolder<T>
  fullName: Microsoft.ApplicationInsights.Extensibility.IOperationHolder<T>
  nameWithType.vb: IOperationHolder(Of T)
  fullName.vb: Microsoft.ApplicationInsights.Extensibility.IOperationHolder(Of T)
  name.vb: IOperationHolder(Of T)
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
    name: IOperationHolder
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.IOperationHolder-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
    name: IOperationHolder
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.IOperationHolder-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter
  commentId: T:Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.html
  name: ISerializableWithWriter
  nameWithType: ISerializableWithWriter
  fullName: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter
- uid: Microsoft.ApplicationInsights.Extensibility.ISerializationWriter
  commentId: T:Microsoft.ApplicationInsights.Extensibility.ISerializationWriter
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.ISerializationWriter.html
  name: ISerializationWriter
  nameWithType: ISerializationWriter
  fullName: Microsoft.ApplicationInsights.Extensibility.ISerializationWriter
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  commentId: T:Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.html
  name: ITelemetryInitializer
  nameWithType: ITelemetryInitializer
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule
  commentId: T:Microsoft.ApplicationInsights.Extensibility.ITelemetryModule
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.html
  name: ITelemetryModule
  nameWithType: ITelemetryModule
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor
  commentId: T:Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.html
  name: ITelemetryProcessor
  nameWithType: ITelemetryProcessor
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor
- uid: Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer
  commentId: T:Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer.html
  name: OperationCorrelationTelemetryInitializer
  nameWithType: OperationCorrelationTelemetryInitializer
  fullName: Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer
- uid: Microsoft.ApplicationInsights.Extensibility.SdkInternalOperationsMonitor
  commentId: T:Microsoft.ApplicationInsights.Extensibility.SdkInternalOperationsMonitor
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.SdkInternalOperationsMonitor.html
  name: SdkInternalOperationsMonitor
  nameWithType: SdkInternalOperationsMonitor
  fullName: Microsoft.ApplicationInsights.Extensibility.SdkInternalOperationsMonitor
- uid: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer
  commentId: T:Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.html
  name: SequencePropertyInitializer
  nameWithType: SequencePropertyInitializer
  fullName: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer
- uid: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
  commentId: T:Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.html
  name: TelemetryConfiguration
  nameWithType: TelemetryConfiguration
  fullName: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
- uid: Microsoft.ApplicationInsights.Extensibility.TelemetrySink
  commentId: T:Microsoft.ApplicationInsights.Extensibility.TelemetrySink
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.TelemetrySink.html
  name: TelemetrySink
  nameWithType: TelemetrySink
  fullName: Microsoft.ApplicationInsights.Extensibility.TelemetrySink
- uid: Microsoft.ApplicationInsights.Extensibility.AutocollectedMetricsExtractor
  commentId: T:Microsoft.ApplicationInsights.Extensibility.AutocollectedMetricsExtractor
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.AutocollectedMetricsExtractor.html
  name: AutocollectedMetricsExtractor
  nameWithType: AutocollectedMetricsExtractor
  fullName: Microsoft.ApplicationInsights.Extensibility.AutocollectedMetricsExtractor
- uid: Microsoft.ApplicationInsights.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
