### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.DataContracts.ISupportSampling
  commentId: T:Microsoft.ApplicationInsights.DataContracts.ISupportSampling
  id: ISupportSampling
  parent: Microsoft.ApplicationInsights.DataContracts
  children:
  - Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage
  langs:
  - csharp
  - vb
  name: ISupportSampling
  nameWithType: ISupportSampling
  fullName: Microsoft.ApplicationInsights.DataContracts.ISupportSampling
  type: Interface
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: public interface ISupportSampling
    content.vb: Public Interface ISupportSampling
- uid: Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage
  commentId: P:Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage
  id: SamplingPercentage
  parent: Microsoft.ApplicationInsights.DataContracts.ISupportSampling
  langs:
  - csharp
  - vb
  name: SamplingPercentage
  nameWithType: ISupportSampling.SamplingPercentage
  fullName: Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage
  type: Property
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: double? SamplingPercentage { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Double}
    content.vb: Property SamplingPercentage As Double?
  overload: Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage*
references:
- uid: Microsoft.ApplicationInsights.DataContracts
  commentId: N:Microsoft.ApplicationInsights.DataContracts
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.DataContracts
  nameWithType: Microsoft.ApplicationInsights.DataContracts
  fullName: Microsoft.ApplicationInsights.DataContracts
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.DataContracts
    name: DataContracts
    isExternal: true
    href: Microsoft.ApplicationInsights.DataContracts.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.DataContracts
    name: DataContracts
    isExternal: true
    href: Microsoft.ApplicationInsights.DataContracts.html
- uid: Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage*
  commentId: Overload:Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage
  isExternal: true
  href: Microsoft.ApplicationInsights.DataContracts.ISupportSampling.html#Microsoft_ApplicationInsights_DataContracts_ISupportSampling_SamplingPercentage
  name: SamplingPercentage
  nameWithType: ISupportSampling.SamplingPercentage
  fullName: Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage
- uid: System.Nullable{System.Double}
  commentId: T:System.Nullable{System.Double}
  parent: System
  definition: System.Nullable`1
  href: https://learn.microsoft.com/dotnet/api/system.double
  name: double?
  nameWithType: double?
  fullName: double?
  nameWithType.vb: Double?
  fullName.vb: Double?
  name.vb: Double?
  spec.csharp:
  - uid: System.Double
    name: double
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.double
  - name: '?'
  spec.vb:
  - uid: System.Double
    name: Double
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.double
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
