### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId
  commentId: N:Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId
  id: Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId.ApplicationInsightsApplicationIdProvider
  - Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId.DictionaryApplicationIdProvider
  langs:
  - csharp
  - vb
  name: Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId
  nameWithType: Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId
  type: Namespace
  assemblies:
  - Microsoft.ApplicationInsights
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId.ApplicationInsightsApplicationIdProvider
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId.ApplicationInsightsApplicationIdProvider
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId.ApplicationInsightsApplicationIdProvider.html
  name: ApplicationInsightsApplicationIdProvider
  nameWithType: ApplicationInsightsApplicationIdProvider
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId.ApplicationInsightsApplicationIdProvider
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId.DictionaryApplicationIdProvider
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId.DictionaryApplicationIdProvider
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId.DictionaryApplicationIdProvider.html
  name: DictionaryApplicationIdProvider
  nameWithType: DictionaryApplicationIdProvider
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId.DictionaryApplicationIdProvider
