### YamlMime:ManagedReference
items:
- uid: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables
  commentId: T:Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables
  id: IEnvironmentVariables
  parent: Microsoft.Testing.Platform.Extensions.TestHostControllers
  children:
  - Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.RemoveVariable(System.String)
  - Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.SetVariable(Microsoft.Testing.Platform.Extensions.TestHostControllers.EnvironmentVariable)
  langs:
  - csharp
  - vb
  name: IEnvironmentVariables
  nameWithType: IEnvironmentVariables
  fullName: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables
  type: Interface
  assemblies:
  - Microsoft.Testing.Platform
  namespace: Microsoft.Testing.Platform.Extensions.TestHostControllers
  syntax:
    content: 'public interface IEnvironmentVariables : IReadOnlyEnvironmentVariables'
    content.vb: Public Interface IEnvironmentVariables Inherits IReadOnlyEnvironmentVariables
  inheritedMembers:
  - Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.TryGetVariable(System.String,Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable@)
- uid: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.SetVariable(Microsoft.Testing.Platform.Extensions.TestHostControllers.EnvironmentVariable)
  commentId: M:Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.SetVariable(Microsoft.Testing.Platform.Extensions.TestHostControllers.EnvironmentVariable)
  id: SetVariable(Microsoft.Testing.Platform.Extensions.TestHostControllers.EnvironmentVariable)
  parent: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables
  langs:
  - csharp
  - vb
  name: SetVariable(EnvironmentVariable)
  nameWithType: IEnvironmentVariables.SetVariable(EnvironmentVariable)
  fullName: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.SetVariable(Microsoft.Testing.Platform.Extensions.TestHostControllers.EnvironmentVariable)
  type: Method
  assemblies:
  - Microsoft.Testing.Platform
  namespace: Microsoft.Testing.Platform.Extensions.TestHostControllers
  syntax:
    content: void SetVariable(EnvironmentVariable environmentVariable)
    parameters:
    - id: environmentVariable
      type: Microsoft.Testing.Platform.Extensions.TestHostControllers.EnvironmentVariable
    content.vb: Sub SetVariable(environmentVariable As EnvironmentVariable)
  overload: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.SetVariable*
- uid: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.RemoveVariable(System.String)
  commentId: M:Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.RemoveVariable(System.String)
  id: RemoveVariable(System.String)
  parent: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables
  langs:
  - csharp
  - vb
  name: RemoveVariable(string)
  nameWithType: IEnvironmentVariables.RemoveVariable(string)
  fullName: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.RemoveVariable(string)
  type: Method
  assemblies:
  - Microsoft.Testing.Platform
  namespace: Microsoft.Testing.Platform.Extensions.TestHostControllers
  syntax:
    content: void RemoveVariable(string variable)
    parameters:
    - id: variable
      type: System.String
    content.vb: Sub RemoveVariable(variable As String)
  overload: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.RemoveVariable*
  nameWithType.vb: IEnvironmentVariables.RemoveVariable(String)
  fullName.vb: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.RemoveVariable(String)
  name.vb: RemoveVariable(String)
references:
- uid: Microsoft.Testing.Platform.Extensions.TestHostControllers
  commentId: N:Microsoft.Testing.Platform.Extensions.TestHostControllers
  isExternal: true
  href: Microsoft.html
  name: Microsoft.Testing.Platform.Extensions.TestHostControllers
  nameWithType: Microsoft.Testing.Platform.Extensions.TestHostControllers
  fullName: Microsoft.Testing.Platform.Extensions.TestHostControllers
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Testing
    name: Testing
    isExternal: true
    href: Microsoft.Testing.html
  - name: .
  - uid: Microsoft.Testing.Platform
    name: Platform
    isExternal: true
    href: Microsoft.Testing.Platform.html
  - name: .
  - uid: Microsoft.Testing.Platform.Extensions
    name: Extensions
    isExternal: true
    href: Microsoft.Testing.Platform.Extensions.html
  - name: .
  - uid: Microsoft.Testing.Platform.Extensions.TestHostControllers
    name: TestHostControllers
    isExternal: true
    href: Microsoft.Testing.Platform.Extensions.TestHostControllers.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Testing
    name: Testing
    isExternal: true
    href: Microsoft.Testing.html
  - name: .
  - uid: Microsoft.Testing.Platform
    name: Platform
    isExternal: true
    href: Microsoft.Testing.Platform.html
  - name: .
  - uid: Microsoft.Testing.Platform.Extensions
    name: Extensions
    isExternal: true
    href: Microsoft.Testing.Platform.Extensions.html
  - name: .
  - uid: Microsoft.Testing.Platform.Extensions.TestHostControllers
    name: TestHostControllers
    isExternal: true
    href: Microsoft.Testing.Platform.Extensions.TestHostControllers.html
- uid: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.TryGetVariable(System.String,Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable@)
  commentId: M:Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.TryGetVariable(System.String,Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable@)
  parent: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables
  isExternal: true
  href: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.html#Microsoft_Testing_Platform_Extensions_TestHostControllers_IReadOnlyEnvironmentVariables_TryGetVariable_System_String_Microsoft_Testing_Platform_Extensions_TestHostControllers_OwnedEnvironmentVariable__
  name: TryGetVariable(string, out OwnedEnvironmentVariable)
  nameWithType: IReadOnlyEnvironmentVariables.TryGetVariable(string, out OwnedEnvironmentVariable)
  fullName: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.TryGetVariable(string, out Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable)
  nameWithType.vb: IReadOnlyEnvironmentVariables.TryGetVariable(String, OwnedEnvironmentVariable)
  fullName.vb: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.TryGetVariable(String, Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable)
  name.vb: TryGetVariable(String, OwnedEnvironmentVariable)
  spec.csharp:
  - uid: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.TryGetVariable(System.String,Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable@)
    name: TryGetVariable
    isExternal: true
    href: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.html#Microsoft_Testing_Platform_Extensions_TestHostControllers_IReadOnlyEnvironmentVariables_TryGetVariable_System_String_Microsoft_Testing_Platform_Extensions_TestHostControllers_OwnedEnvironmentVariable__
  - name: (
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - name: out
  - name: " "
  - uid: Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable
    name: OwnedEnvironmentVariable
    isExternal: true
    href: Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable.html
  - name: )
  spec.vb:
  - uid: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.TryGetVariable(System.String,Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable@)
    name: TryGetVariable
    isExternal: true
    href: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.html#Microsoft_Testing_Platform_Extensions_TestHostControllers_IReadOnlyEnvironmentVariables_TryGetVariable_System_String_Microsoft_Testing_Platform_Extensions_TestHostControllers_OwnedEnvironmentVariable__
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable
    name: OwnedEnvironmentVariable
    isExternal: true
    href: Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable.html
  - name: )
- uid: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables
  commentId: T:Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables
  parent: Microsoft.Testing.Platform.Extensions.TestHostControllers
  isExternal: true
  href: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.html
  name: IReadOnlyEnvironmentVariables
  nameWithType: IReadOnlyEnvironmentVariables
  fullName: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables
- uid: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.SetVariable*
  commentId: Overload:Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.SetVariable
  isExternal: true
  href: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.html#Microsoft_Testing_Platform_Extensions_TestHostControllers_IEnvironmentVariables_SetVariable_Microsoft_Testing_Platform_Extensions_TestHostControllers_EnvironmentVariable_
  name: SetVariable
  nameWithType: IEnvironmentVariables.SetVariable
  fullName: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.SetVariable
- uid: Microsoft.Testing.Platform.Extensions.TestHostControllers.EnvironmentVariable
  commentId: T:Microsoft.Testing.Platform.Extensions.TestHostControllers.EnvironmentVariable
  parent: Microsoft.Testing.Platform.Extensions.TestHostControllers
  isExternal: true
  href: Microsoft.Testing.Platform.Extensions.TestHostControllers.EnvironmentVariable.html
  name: EnvironmentVariable
  nameWithType: EnvironmentVariable
  fullName: Microsoft.Testing.Platform.Extensions.TestHostControllers.EnvironmentVariable
- uid: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.RemoveVariable*
  commentId: Overload:Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.RemoveVariable
  isExternal: true
  href: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.html#Microsoft_Testing_Platform_Extensions_TestHostControllers_IEnvironmentVariables_RemoveVariable_System_String_
  name: RemoveVariable
  nameWithType: IEnvironmentVariables.RemoveVariable
  fullName: Microsoft.Testing.Platform.Extensions.TestHostControllers.IEnvironmentVariables.RemoveVariable
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
