### YamlMime:ManagedReference
items:
- uid: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables
  commentId: T:Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables
  id: IReadOnlyEnvironmentVariables
  parent: Microsoft.Testing.Platform.Extensions.TestHostControllers
  children:
  - Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.TryGetVariable(System.String,Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable@)
  langs:
  - csharp
  - vb
  name: IReadOnlyEnvironmentVariables
  nameWithType: IReadOnlyEnvironmentVariables
  fullName: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables
  type: Interface
  assemblies:
  - Microsoft.Testing.Platform
  namespace: Microsoft.Testing.Platform.Extensions.TestHostControllers
  syntax:
    content: public interface IReadOnlyEnvironmentVariables
    content.vb: Public Interface IReadOnlyEnvironmentVariables
- uid: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.TryGetVariable(System.String,Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable@)
  commentId: M:Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.TryGetVariable(System.String,Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable@)
  id: TryGetVariable(System.String,Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable@)
  parent: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables
  langs:
  - csharp
  - vb
  name: TryGetVariable(string, out OwnedEnvironmentVariable?)
  nameWithType: IReadOnlyEnvironmentVariables.TryGetVariable(string, out OwnedEnvironmentVariable?)
  fullName: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.TryGetVariable(string, out Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable?)
  type: Method
  assemblies:
  - Microsoft.Testing.Platform
  namespace: Microsoft.Testing.Platform.Extensions.TestHostControllers
  syntax:
    content: bool TryGetVariable(string variable, out OwnedEnvironmentVariable? environmentVariable)
    parameters:
    - id: variable
      type: System.String
    - id: environmentVariable
      type: Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable
    return:
      type: System.Boolean
    content.vb: Function TryGetVariable(variable As String, environmentVariable As OwnedEnvironmentVariable) As Boolean
  overload: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.TryGetVariable*
  nameWithType.vb: IReadOnlyEnvironmentVariables.TryGetVariable(String, OwnedEnvironmentVariable)
  fullName.vb: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.TryGetVariable(String, Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable)
  name.vb: TryGetVariable(String, OwnedEnvironmentVariable)
references:
- uid: Microsoft.Testing.Platform.Extensions.TestHostControllers
  commentId: N:Microsoft.Testing.Platform.Extensions.TestHostControllers
  isExternal: true
  href: Microsoft.html
  name: Microsoft.Testing.Platform.Extensions.TestHostControllers
  nameWithType: Microsoft.Testing.Platform.Extensions.TestHostControllers
  fullName: Microsoft.Testing.Platform.Extensions.TestHostControllers
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Testing
    name: Testing
    isExternal: true
    href: Microsoft.Testing.html
  - name: .
  - uid: Microsoft.Testing.Platform
    name: Platform
    isExternal: true
    href: Microsoft.Testing.Platform.html
  - name: .
  - uid: Microsoft.Testing.Platform.Extensions
    name: Extensions
    isExternal: true
    href: Microsoft.Testing.Platform.Extensions.html
  - name: .
  - uid: Microsoft.Testing.Platform.Extensions.TestHostControllers
    name: TestHostControllers
    isExternal: true
    href: Microsoft.Testing.Platform.Extensions.TestHostControllers.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Testing
    name: Testing
    isExternal: true
    href: Microsoft.Testing.html
  - name: .
  - uid: Microsoft.Testing.Platform
    name: Platform
    isExternal: true
    href: Microsoft.Testing.Platform.html
  - name: .
  - uid: Microsoft.Testing.Platform.Extensions
    name: Extensions
    isExternal: true
    href: Microsoft.Testing.Platform.Extensions.html
  - name: .
  - uid: Microsoft.Testing.Platform.Extensions.TestHostControllers
    name: TestHostControllers
    isExternal: true
    href: Microsoft.Testing.Platform.Extensions.TestHostControllers.html
- uid: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.TryGetVariable*
  commentId: Overload:Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.TryGetVariable
  isExternal: true
  href: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.html#Microsoft_Testing_Platform_Extensions_TestHostControllers_IReadOnlyEnvironmentVariables_TryGetVariable_System_String_Microsoft_Testing_Platform_Extensions_TestHostControllers_OwnedEnvironmentVariable__
  name: TryGetVariable
  nameWithType: IReadOnlyEnvironmentVariables.TryGetVariable
  fullName: Microsoft.Testing.Platform.Extensions.TestHostControllers.IReadOnlyEnvironmentVariables.TryGetVariable
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable
  commentId: T:Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable
  parent: Microsoft.Testing.Platform.Extensions.TestHostControllers
  isExternal: true
  href: Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable.html
  name: OwnedEnvironmentVariable
  nameWithType: OwnedEnvironmentVariable
  fullName: Microsoft.Testing.Platform.Extensions.TestHostControllers.OwnedEnvironmentVariable
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
