### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings
  commentId: T:Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings
  id: IRunSettings
  parent: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  children:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.GetSettings(System.String)
  - Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.SettingsXml
  langs:
  - csharp
  - vb
  name: IRunSettings
  nameWithType: IRunSettings
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings
  type: Interface
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel
  namespace: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  syntax:
    content: public interface IRunSettings
    content.vb: Public Interface IRunSettings
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.GetSettings(System.String)
  commentId: M:Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.GetSettings(System.String)
  id: GetSettings(System.String)
  parent: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings
  langs:
  - csharp
  - vb
  name: GetSettings(string?)
  nameWithType: IRunSettings.GetSettings(string?)
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.GetSettings(string?)
  type: Method
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel
  namespace: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  syntax:
    content: ISettingsProvider? GetSettings(string? settingsName)
    parameters:
    - id: settingsName
      type: System.String
    return:
      type: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider
    content.vb: Function GetSettings(settingsName As String) As ISettingsProvider
  overload: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.GetSettings*
  nameWithType.vb: IRunSettings.GetSettings(String)
  fullName.vb: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.GetSettings(String)
  name.vb: GetSettings(String)
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.SettingsXml
  commentId: P:Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.SettingsXml
  id: SettingsXml
  parent: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings
  langs:
  - csharp
  - vb
  name: SettingsXml
  nameWithType: IRunSettings.SettingsXml
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.SettingsXml
  type: Property
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel
  namespace: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  syntax:
    content: string? SettingsXml { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property SettingsXml As String
  overload: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.SettingsXml*
references:
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  commentId: N:Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  isExternal: true
  href: Microsoft.html
  name: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  nameWithType: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel
    name: ObjectModel
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
    name: Adapter
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel
    name: ObjectModel
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
    name: Adapter
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.html
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.GetSettings*
  commentId: Overload:Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.GetSettings
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.html#Microsoft_VisualStudio_TestPlatform_ObjectModel_Adapter_IRunSettings_GetSettings_System_String_
  name: GetSettings
  nameWithType: IRunSettings.GetSettings
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.GetSettings
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider
  commentId: T:Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider
  parent: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.html
  name: ISettingsProvider
  nameWithType: ISettingsProvider
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.SettingsXml*
  commentId: Overload:Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.SettingsXml
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.html#Microsoft_VisualStudio_TestPlatform_ObjectModel_Adapter_IRunSettings_SettingsXml
  name: SettingsXml
  nameWithType: IRunSettings.SettingsXml
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings.SettingsXml
