### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces.IDataCollectorsSettingsProvider
  commentId: T:Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces.IDataCollectorsSettingsProvider
  id: IDataCollectorsSettingsProvider
  parent: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces
  children:
  - Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces.IDataCollectorsSettingsProvider.Settings
  langs:
  - csharp
  - vb
  name: IDataCollectorsSettingsProvider
  nameWithType: IDataCollectorsSettingsProvider
  fullName: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces.IDataCollectorsSettingsProvider
  type: Interface
  assemblies:
  - Microsoft.TestPlatform.CrossPlatEngine
  namespace: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces
  syntax:
    content: 'public interface IDataCollectorsSettingsProvider : ISettingsProvider'
    content.vb: Public Interface IDataCollectorsSettingsProvider Inherits ISettingsProvider
  inheritedMembers:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.Load(System.Xml.XmlReader)
- uid: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces.IDataCollectorsSettingsProvider.Settings
  commentId: P:Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces.IDataCollectorsSettingsProvider.Settings
  id: Settings
  parent: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces.IDataCollectorsSettingsProvider
  langs:
  - csharp
  - vb
  name: Settings
  nameWithType: IDataCollectorsSettingsProvider.Settings
  fullName: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces.IDataCollectorsSettingsProvider.Settings
  type: Property
  assemblies:
  - Microsoft.TestPlatform.CrossPlatEngine
  namespace: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces
  syntax:
    content: DataCollectionRunSettings Settings { get; }
    parameters: []
    return:
      type: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollectionRunSettings
    content.vb: ReadOnly Property Settings As DataCollectionRunSettings
  overload: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces.IDataCollectorsSettingsProvider.Settings*
references:
- uid: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces
  commentId: N:Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces
  isExternal: true
  href: Microsoft.html
  name: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces
  nameWithType: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces
  fullName: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine
    name: CrossPlatEngine
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection
    name: DataCollection
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces
    name: Interfaces
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine
    name: CrossPlatEngine
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection
    name: DataCollection
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces
    name: Interfaces
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces.html
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.Load(System.Xml.XmlReader)
  commentId: M:Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.Load(System.Xml.XmlReader)
  parent: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider
  isExternal: true
  name: Load(XmlReader)
  nameWithType: ISettingsProvider.Load(XmlReader)
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.Load(System.Xml.XmlReader)
  spec.csharp:
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.Load(System.Xml.XmlReader)
    name: Load
    isExternal: true
  - name: (
  - uid: System.Xml.XmlReader
    name: XmlReader
    isExternal: true
  - name: )
  spec.vb:
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.Load(System.Xml.XmlReader)
    name: Load
    isExternal: true
  - name: (
  - uid: System.Xml.XmlReader
    name: XmlReader
    isExternal: true
  - name: )
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider
  commentId: T:Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider
  parent: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.html
  name: ISettingsProvider
  nameWithType: ISettingsProvider
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  commentId: N:Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  isExternal: true
  href: Microsoft.html
  name: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  nameWithType: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel
    name: ObjectModel
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
    name: Adapter
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel
    name: ObjectModel
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
    name: Adapter
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.html
- uid: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces.IDataCollectorsSettingsProvider.Settings*
  commentId: Overload:Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces.IDataCollectorsSettingsProvider.Settings
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces.IDataCollectorsSettingsProvider.html#Microsoft_VisualStudio_TestPlatform_CrossPlatEngine_DataCollection_Interfaces_IDataCollectorsSettingsProvider_Settings
  name: Settings
  nameWithType: IDataCollectorsSettingsProvider.Settings
  fullName: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces.IDataCollectorsSettingsProvider.Settings
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollectionRunSettings
  commentId: T:Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollectionRunSettings
  parent: Microsoft.VisualStudio.TestPlatform.ObjectModel
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollectionRunSettings.html
  name: DataCollectionRunSettings
  nameWithType: DataCollectionRunSettings
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollectionRunSettings
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel
  commentId: N:Microsoft.VisualStudio.TestPlatform.ObjectModel
  isExternal: true
  href: Microsoft.html
  name: Microsoft.VisualStudio.TestPlatform.ObjectModel
  nameWithType: Microsoft.VisualStudio.TestPlatform.ObjectModel
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel
    name: ObjectModel
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel
    name: ObjectModel
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.html
