### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling
  commentId: T:Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling
  id: ISupportAdvancedSampling
  parent: Microsoft.ApplicationInsights.DataContracts
  children:
  - Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.ItemTypeFlag
  - Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.ProactiveSamplingDecision
  langs:
  - csharp
  - vb
  name: ISupportAdvancedSampling
  nameWithType: ISupportAdvancedSampling
  fullName: Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling
  type: Interface
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: 'public interface ISupportAdvancedSampling : ISupportSampling'
    content.vb: Public Interface ISupportAdvancedSampling Inherits ISupportSampling
  inheritedMembers:
  - Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage
- uid: Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.ItemTypeFlag
  commentId: P:Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.ItemTypeFlag
  id: ItemTypeFlag
  parent: Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling
  langs:
  - csharp
  - vb
  name: ItemTypeFlag
  nameWithType: ISupportAdvancedSampling.ItemTypeFlag
  fullName: Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.ItemTypeFlag
  type: Property
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: SamplingTelemetryItemTypes ItemTypeFlag { get; }
    parameters: []
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
    content.vb: ReadOnly Property ItemTypeFlag As SamplingTelemetryItemTypes
  overload: Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.ItemTypeFlag*
- uid: Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.ProactiveSamplingDecision
  commentId: P:Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.ProactiveSamplingDecision
  id: ProactiveSamplingDecision
  parent: Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling
  langs:
  - csharp
  - vb
  name: ProactiveSamplingDecision
  nameWithType: ISupportAdvancedSampling.ProactiveSamplingDecision
  fullName: Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.ProactiveSamplingDecision
  type: Property
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: SamplingDecision ProactiveSamplingDecision { get; set; }
    parameters: []
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingDecision
    content.vb: Property ProactiveSamplingDecision As SamplingDecision
  overload: Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.ProactiveSamplingDecision*
references:
- uid: Microsoft.ApplicationInsights.DataContracts
  commentId: N:Microsoft.ApplicationInsights.DataContracts
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.DataContracts
  nameWithType: Microsoft.ApplicationInsights.DataContracts
  fullName: Microsoft.ApplicationInsights.DataContracts
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.DataContracts
    name: DataContracts
    isExternal: true
    href: Microsoft.ApplicationInsights.DataContracts.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.DataContracts
    name: DataContracts
    isExternal: true
    href: Microsoft.ApplicationInsights.DataContracts.html
- uid: Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage
  commentId: P:Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage
  parent: Microsoft.ApplicationInsights.DataContracts.ISupportSampling
  isExternal: true
  href: Microsoft.ApplicationInsights.DataContracts.ISupportSampling.html#Microsoft_ApplicationInsights_DataContracts_ISupportSampling_SamplingPercentage
  name: SamplingPercentage
  nameWithType: ISupportSampling.SamplingPercentage
  fullName: Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage
- uid: Microsoft.ApplicationInsights.DataContracts.ISupportSampling
  commentId: T:Microsoft.ApplicationInsights.DataContracts.ISupportSampling
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: true
  href: Microsoft.ApplicationInsights.DataContracts.ISupportSampling.html
  name: ISupportSampling
  nameWithType: ISupportSampling
  fullName: Microsoft.ApplicationInsights.DataContracts.ISupportSampling
- uid: Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.ItemTypeFlag*
  commentId: Overload:Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.ItemTypeFlag
  isExternal: true
  href: Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.html#Microsoft_ApplicationInsights_DataContracts_ISupportAdvancedSampling_ItemTypeFlag
  name: ItemTypeFlag
  nameWithType: ISupportAdvancedSampling.ItemTypeFlag
  fullName: Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.ItemTypeFlag
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  commentId: T:Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: true
  href: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.html
  name: SamplingTelemetryItemTypes
  nameWithType: SamplingTelemetryItemTypes
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
- uid: Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.ProactiveSamplingDecision*
  commentId: Overload:Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.ProactiveSamplingDecision
  isExternal: true
  href: Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.html#Microsoft_ApplicationInsights_DataContracts_ISupportAdvancedSampling_ProactiveSamplingDecision
  name: ProactiveSamplingDecision
  nameWithType: ISupportAdvancedSampling.ProactiveSamplingDecision
  fullName: Microsoft.ApplicationInsights.DataContracts.ISupportAdvancedSampling.ProactiveSamplingDecision
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingDecision
  commentId: T:Microsoft.ApplicationInsights.DataContracts.SamplingDecision
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: true
  href: Microsoft.ApplicationInsights.DataContracts.SamplingDecision.html
  name: SamplingDecision
  nameWithType: SamplingDecision
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingDecision
