### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider
  commentId: N:Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider
  id: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider
  children:
  - Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider.SettingsProviderExtensionManager
  langs:
  - csharp
  - vb
  name: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider
  nameWithType: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider
  fullName: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider
  type: Namespace
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.Common
references:
- uid: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider.SettingsProviderExtensionManager
  commentId: T:Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider.SettingsProviderExtensionManager
  parent: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider.SettingsProviderExtensionManager.html
  name: SettingsProviderExtensionManager
  nameWithType: SettingsProviderExtensionManager
  fullName: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider.SettingsProviderExtensionManager
- uid: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider
  commentId: N:Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider
  isExternal: true
  href: Microsoft.html
  name: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider
  nameWithType: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider
  fullName: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.Common
    name: Common
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.Common.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider
    name: SettingsProvider
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.Common
    name: Common
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.Common.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider
    name: SettingsProvider
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider.html
