### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights
  commentId: N:Microsoft.ApplicationInsights
  id: Microsoft.ApplicationInsights
  children:
  - Microsoft.ApplicationInsights.Metric
  - Microsoft.ApplicationInsights.MetricAggregationScope
  - Microsoft.ApplicationInsights.MetricConfigurations
  - Microsoft.ApplicationInsights.MetricDimensionNames
  - Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
  - Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Cloud
  - Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Component
  - Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
  - Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Location
  - Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Operation
  - Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Session
  - Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.User
  - Microsoft.ApplicationInsights.TelemetryClient
  langs:
  - csharp
  - vb
  name: Microsoft.ApplicationInsights
  nameWithType: Microsoft.ApplicationInsights
  fullName: Microsoft.ApplicationInsights
  type: Namespace
  assemblies:
  - Microsoft.ApplicationInsights
references:
- uid: Microsoft.ApplicationInsights.Metric
  commentId: T:Microsoft.ApplicationInsights.Metric
  parent: Microsoft.ApplicationInsights
  isExternal: true
  href: Microsoft.ApplicationInsights.Metric.html
  name: Metric
  nameWithType: Metric
  fullName: Microsoft.ApplicationInsights.Metric
- uid: Microsoft.ApplicationInsights.MetricAggregationScope
  commentId: T:Microsoft.ApplicationInsights.MetricAggregationScope
  parent: Microsoft.ApplicationInsights
  isExternal: true
  href: Microsoft.ApplicationInsights.MetricAggregationScope.html
  name: MetricAggregationScope
  nameWithType: MetricAggregationScope
  fullName: Microsoft.ApplicationInsights.MetricAggregationScope
- uid: Microsoft.ApplicationInsights.MetricConfigurations
  commentId: T:Microsoft.ApplicationInsights.MetricConfigurations
  parent: Microsoft.ApplicationInsights
  isExternal: true
  href: Microsoft.ApplicationInsights.MetricConfigurations.html
  name: MetricConfigurations
  nameWithType: MetricConfigurations
  fullName: Microsoft.ApplicationInsights.MetricConfigurations
- uid: Microsoft.ApplicationInsights.MetricDimensionNames
  commentId: T:Microsoft.ApplicationInsights.MetricDimensionNames
  isExternal: true
  href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  name: MetricDimensionNames
  nameWithType: MetricDimensionNames
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
  commentId: T:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
  isExternal: true
  href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  name: MetricDimensionNames.TelemetryContext
  nameWithType: MetricDimensionNames.TelemetryContext
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames
    name: MetricDimensionNames
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
    name: TelemetryContext
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.html
  spec.vb:
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames
    name: MetricDimensionNames
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
    name: TelemetryContext
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.html
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Cloud
  commentId: T:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Cloud
  isExternal: true
  href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  name: MetricDimensionNames.TelemetryContext.Cloud
  nameWithType: MetricDimensionNames.TelemetryContext.Cloud
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Cloud
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames
    name: MetricDimensionNames
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
    name: TelemetryContext
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Cloud
    name: Cloud
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Cloud.html
  spec.vb:
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames
    name: MetricDimensionNames
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
    name: TelemetryContext
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Cloud
    name: Cloud
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Cloud.html
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Component
  commentId: T:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Component
  isExternal: true
  href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  name: MetricDimensionNames.TelemetryContext.Component
  nameWithType: MetricDimensionNames.TelemetryContext.Component
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Component
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames
    name: MetricDimensionNames
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
    name: TelemetryContext
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Component
    name: Component
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Component.html
  spec.vb:
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames
    name: MetricDimensionNames
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
    name: TelemetryContext
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Component
    name: Component
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Component.html
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
  commentId: T:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
  isExternal: true
  href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  name: MetricDimensionNames.TelemetryContext.Device
  nameWithType: MetricDimensionNames.TelemetryContext.Device
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames
    name: MetricDimensionNames
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
    name: TelemetryContext
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
    name: Device
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.html
  spec.vb:
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames
    name: MetricDimensionNames
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
    name: TelemetryContext
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device
    name: Device
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Device.html
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Location
  commentId: T:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Location
  isExternal: true
  href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  name: MetricDimensionNames.TelemetryContext.Location
  nameWithType: MetricDimensionNames.TelemetryContext.Location
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Location
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames
    name: MetricDimensionNames
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
    name: TelemetryContext
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Location
    name: Location
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Location.html
  spec.vb:
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames
    name: MetricDimensionNames
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
    name: TelemetryContext
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Location
    name: Location
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Location.html
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Operation
  commentId: T:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Operation
  isExternal: true
  href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  name: MetricDimensionNames.TelemetryContext.Operation
  nameWithType: MetricDimensionNames.TelemetryContext.Operation
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Operation
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames
    name: MetricDimensionNames
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
    name: TelemetryContext
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Operation
    name: Operation
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Operation.html
  spec.vb:
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames
    name: MetricDimensionNames
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
    name: TelemetryContext
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Operation
    name: Operation
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Operation.html
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Session
  commentId: T:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Session
  isExternal: true
  href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  name: MetricDimensionNames.TelemetryContext.Session
  nameWithType: MetricDimensionNames.TelemetryContext.Session
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Session
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames
    name: MetricDimensionNames
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
    name: TelemetryContext
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Session
    name: Session
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Session.html
  spec.vb:
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames
    name: MetricDimensionNames
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
    name: TelemetryContext
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Session
    name: Session
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.Session.html
- uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.User
  commentId: T:Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.User
  isExternal: true
  href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  name: MetricDimensionNames.TelemetryContext.User
  nameWithType: MetricDimensionNames.TelemetryContext.User
  fullName: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.User
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames
    name: MetricDimensionNames
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
    name: TelemetryContext
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.User
    name: User
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.User.html
  spec.vb:
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames
    name: MetricDimensionNames
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext
    name: TelemetryContext
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.html
  - name: .
  - uid: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.User
    name: User
    isExternal: true
    href: Microsoft.ApplicationInsights.MetricDimensionNames.TelemetryContext.User.html
- uid: Microsoft.ApplicationInsights.TelemetryClient
  commentId: T:Microsoft.ApplicationInsights.TelemetryClient
  parent: Microsoft.ApplicationInsights
  isExternal: true
  href: Microsoft.ApplicationInsights.TelemetryClient.html
  name: TelemetryClient
  nameWithType: TelemetryClient
  fullName: Microsoft.ApplicationInsights.TelemetryClient
- uid: Microsoft.ApplicationInsights
  commentId: N:Microsoft.ApplicationInsights
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights
  nameWithType: Microsoft.ApplicationInsights
  fullName: Microsoft.ApplicationInsights
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
