### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration
  commentId: T:Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration
  id: IMetricSeriesConfiguration
  parent: Microsoft.ApplicationInsights.Metrics
  children:
  - Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.CreateNewAggregator(Microsoft.ApplicationInsights.Metrics.MetricSeries,Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind)
  - Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.RequiresPersistentAggregation
  langs:
  - csharp
  - vb
  name: IMetricSeriesConfiguration
  nameWithType: IMetricSeriesConfiguration
  fullName: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration
  type: Interface
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Metrics
  syntax:
    content: 'public interface IMetricSeriesConfiguration : IEquatable<IMetricSeriesConfiguration>'
    content.vb: Public Interface IMetricSeriesConfiguration Inherits IEquatable(Of IMetricSeriesConfiguration)
  inheritedMembers:
  - System.IEquatable{Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration}.Equals(Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration)
- uid: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.CreateNewAggregator(Microsoft.ApplicationInsights.Metrics.MetricSeries,Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind)
  commentId: M:Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.CreateNewAggregator(Microsoft.ApplicationInsights.Metrics.MetricSeries,Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind)
  id: CreateNewAggregator(Microsoft.ApplicationInsights.Metrics.MetricSeries,Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind)
  parent: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration
  langs:
  - csharp
  - vb
  name: CreateNewAggregator(MetricSeries, MetricAggregationCycleKind)
  nameWithType: IMetricSeriesConfiguration.CreateNewAggregator(MetricSeries, MetricAggregationCycleKind)
  fullName: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.CreateNewAggregator(Microsoft.ApplicationInsights.Metrics.MetricSeries, Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind)
  type: Method
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Metrics
  syntax:
    content: IMetricSeriesAggregator CreateNewAggregator(MetricSeries dataSeries, MetricAggregationCycleKind aggregationCycleKind)
    parameters:
    - id: dataSeries
      type: Microsoft.ApplicationInsights.Metrics.MetricSeries
    - id: aggregationCycleKind
      type: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
    return:
      type: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricSeriesAggregator
    content.vb: Function CreateNewAggregator(dataSeries As MetricSeries, aggregationCycleKind As MetricAggregationCycleKind) As IMetricSeriesAggregator
  overload: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.CreateNewAggregator*
- uid: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.RequiresPersistentAggregation
  commentId: P:Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.RequiresPersistentAggregation
  id: RequiresPersistentAggregation
  parent: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration
  langs:
  - csharp
  - vb
  name: RequiresPersistentAggregation
  nameWithType: IMetricSeriesConfiguration.RequiresPersistentAggregation
  fullName: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.RequiresPersistentAggregation
  type: Property
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Metrics
  syntax:
    content: bool RequiresPersistentAggregation { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property RequiresPersistentAggregation As Boolean
  overload: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.RequiresPersistentAggregation*
references:
- uid: Microsoft.ApplicationInsights.Metrics
  commentId: N:Microsoft.ApplicationInsights.Metrics
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Metrics
  nameWithType: Microsoft.ApplicationInsights.Metrics
  fullName: Microsoft.ApplicationInsights.Metrics
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics
    name: Metrics
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics
    name: Metrics
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.html
- uid: System.IEquatable{Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration}.Equals(Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration)
  commentId: M:System.IEquatable{Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration}.Equals(Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration)
  parent: System.IEquatable{Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration}
  definition: System.IEquatable`1.Equals(`0)
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1.equals
  name: Equals(IMetricSeriesConfiguration)
  nameWithType: IEquatable<IMetricSeriesConfiguration>.Equals(IMetricSeriesConfiguration)
  fullName: System.IEquatable<Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration>.Equals(Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration)
  nameWithType.vb: IEquatable(Of IMetricSeriesConfiguration).Equals(IMetricSeriesConfiguration)
  fullName.vb: System.IEquatable(Of Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration).Equals(Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration)
  spec.csharp:
  - uid: System.IEquatable{Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration}.Equals(Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1.equals
  - name: (
  - uid: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration
    name: IMetricSeriesConfiguration
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.html
  - name: )
  spec.vb:
  - uid: System.IEquatable{Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration}.Equals(Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1.equals
  - name: (
  - uid: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration
    name: IMetricSeriesConfiguration
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.html
  - name: )
- uid: System.IEquatable`1.Equals(`0)
  commentId: M:System.IEquatable`1.Equals(`0)
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1.equals
  name: Equals(T)
  nameWithType: IEquatable<T>.Equals(T)
  fullName: System.IEquatable<T>.Equals(T)
  nameWithType.vb: IEquatable(Of T).Equals(T)
  fullName.vb: System.IEquatable(Of T).Equals(T)
  spec.csharp:
  - uid: System.IEquatable`1.Equals(`0)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1.equals
  - name: (
  - name: T
  - name: )
  spec.vb:
  - uid: System.IEquatable`1.Equals(`0)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1.equals
  - name: (
  - name: T
  - name: )
- uid: System.IEquatable{Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration}
  commentId: T:System.IEquatable{Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration}
  parent: System
  definition: System.IEquatable`1
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<IMetricSeriesConfiguration>
  nameWithType: IEquatable<IMetricSeriesConfiguration>
  fullName: System.IEquatable<Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration>
  nameWithType.vb: IEquatable(Of IMetricSeriesConfiguration)
  fullName.vb: System.IEquatable(Of Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration)
  name.vb: IEquatable(Of IMetricSeriesConfiguration)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - uid: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration
    name: IMetricSeriesConfiguration
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.html
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - uid: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration
    name: IMetricSeriesConfiguration
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.html
  - name: )
- uid: System.IEquatable`1
  commentId: T:System.IEquatable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<T>
  nameWithType: IEquatable<T>
  fullName: System.IEquatable<T>
  nameWithType.vb: IEquatable(Of T)
  fullName.vb: System.IEquatable(Of T)
  name.vb: IEquatable(Of T)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.CreateNewAggregator*
  commentId: Overload:Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.CreateNewAggregator
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.html#Microsoft_ApplicationInsights_Metrics_IMetricSeriesConfiguration_CreateNewAggregator_Microsoft_ApplicationInsights_Metrics_MetricSeries_Microsoft_ApplicationInsights_Metrics_Extensibility_MetricAggregationCycleKind_
  name: CreateNewAggregator
  nameWithType: IMetricSeriesConfiguration.CreateNewAggregator
  fullName: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.CreateNewAggregator
- uid: Microsoft.ApplicationInsights.Metrics.MetricSeries
  commentId: T:Microsoft.ApplicationInsights.Metrics.MetricSeries
  parent: Microsoft.ApplicationInsights.Metrics
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.MetricSeries.html
  name: MetricSeries
  nameWithType: MetricSeries
  fullName: Microsoft.ApplicationInsights.Metrics.MetricSeries
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
  commentId: T:Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind.html
  name: MetricAggregationCycleKind
  nameWithType: MetricAggregationCycleKind
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricSeriesAggregator
  commentId: T:Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricSeriesAggregator
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricSeriesAggregator.html
  name: IMetricSeriesAggregator
  nameWithType: IMetricSeriesAggregator
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricSeriesAggregator
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Metrics.Extensibility
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Metrics.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Metrics.Extensibility
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics
    name: Metrics
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.Extensibility.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics
    name: Metrics
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.Extensibility.html
- uid: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.RequiresPersistentAggregation*
  commentId: Overload:Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.RequiresPersistentAggregation
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.html#Microsoft_ApplicationInsights_Metrics_IMetricSeriesConfiguration_RequiresPersistentAggregation
  name: RequiresPersistentAggregation
  nameWithType: IMetricSeriesConfiguration.RequiresPersistentAggregation
  fullName: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.RequiresPersistentAggregation
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
