### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
  commentId: T:Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
  id: IOperationHolder`1
  parent: Microsoft.ApplicationInsights.Extensibility
  children:
  - Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1.Telemetry
  langs:
  - csharp
  - vb
  name: IOperationHolder<T>
  nameWithType: IOperationHolder<T>
  fullName: Microsoft.ApplicationInsights.Extensibility.IOperationHolder<T>
  type: Interface
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  syntax:
    content: 'public interface IOperationHolder<T> : IDisposable'
    typeParameters:
    - id: T
    content.vb: Public Interface IOperationHolder(Of T) Inherits IDisposable
  inheritedMembers:
  - System.IDisposable.Dispose
  nameWithType.vb: IOperationHolder(Of T)
  fullName.vb: Microsoft.ApplicationInsights.Extensibility.IOperationHolder(Of T)
  name.vb: IOperationHolder(Of T)
- uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1.Telemetry
  commentId: P:Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1.Telemetry
  id: Telemetry
  parent: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
  langs:
  - csharp
  - vb
  name: Telemetry
  nameWithType: IOperationHolder<T>.Telemetry
  fullName: Microsoft.ApplicationInsights.Extensibility.IOperationHolder<T>.Telemetry
  type: Property
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  syntax:
    content: T Telemetry { get; }
    parameters: []
    return:
      type: '{T}'
    content.vb: ReadOnly Property Telemetry As T
  overload: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1.Telemetry*
  nameWithType.vb: IOperationHolder(Of T).Telemetry
  fullName.vb: Microsoft.ApplicationInsights.Extensibility.IOperationHolder(Of T).Telemetry
references:
- uid: Microsoft.ApplicationInsights.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
- uid: System.IDisposable.Dispose
  commentId: M:System.IDisposable.Dispose
  parent: System.IDisposable
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  name: Dispose()
  nameWithType: IDisposable.Dispose()
  fullName: System.IDisposable.Dispose()
  spec.csharp:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
  spec.vb:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
- uid: System.IDisposable
  commentId: T:System.IDisposable
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable
  name: IDisposable
  nameWithType: IDisposable
  fullName: System.IDisposable
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1.Telemetry*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1.Telemetry
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.IOperationHolder-1.html#Microsoft_ApplicationInsights_Extensibility_IOperationHolder_1_Telemetry
  name: Telemetry
  nameWithType: IOperationHolder<T>.Telemetry
  fullName: Microsoft.ApplicationInsights.Extensibility.IOperationHolder<T>.Telemetry
  nameWithType.vb: IOperationHolder(Of T).Telemetry
  fullName.vb: Microsoft.ApplicationInsights.Extensibility.IOperationHolder(Of T).Telemetry
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
