### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Metrics
  commentId: N:Microsoft.ApplicationInsights.Metrics
  id: Microsoft.ApplicationInsights.Metrics
  children:
  - Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration
  - Microsoft.ApplicationInsights.Metrics.MetricAggregate
  - Microsoft.ApplicationInsights.Metrics.MetricConfiguration
  - Microsoft.ApplicationInsights.Metrics.MetricConfigurationForMeasurement
  - Microsoft.ApplicationInsights.Metrics.MetricIdentifier
  - Microsoft.ApplicationInsights.Metrics.MetricManager
  - Microsoft.ApplicationInsights.Metrics.MetricSeries
  - Microsoft.ApplicationInsights.Metrics.MetricSeriesConfigurationForMeasurement
  - Microsoft.ApplicationInsights.Metrics.MetricsCollection
  - Microsoft.ApplicationInsights.Metrics.TelemetryConfigurationExtensions
  langs:
  - csharp
  - vb
  name: Microsoft.ApplicationInsights.Metrics
  nameWithType: Microsoft.ApplicationInsights.Metrics
  fullName: Microsoft.ApplicationInsights.Metrics
  type: Namespace
  assemblies:
  - Microsoft.ApplicationInsights
references:
- uid: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration
  commentId: T:Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration
  parent: Microsoft.ApplicationInsights.Metrics
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration.html
  name: IMetricSeriesConfiguration
  nameWithType: IMetricSeriesConfiguration
  fullName: Microsoft.ApplicationInsights.Metrics.IMetricSeriesConfiguration
- uid: Microsoft.ApplicationInsights.Metrics.MetricAggregate
  commentId: T:Microsoft.ApplicationInsights.Metrics.MetricAggregate
  parent: Microsoft.ApplicationInsights.Metrics
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.MetricAggregate.html
  name: MetricAggregate
  nameWithType: MetricAggregate
  fullName: Microsoft.ApplicationInsights.Metrics.MetricAggregate
- uid: Microsoft.ApplicationInsights.Metrics.MetricConfiguration
  commentId: T:Microsoft.ApplicationInsights.Metrics.MetricConfiguration
  parent: Microsoft.ApplicationInsights.Metrics
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.MetricConfiguration.html
  name: MetricConfiguration
  nameWithType: MetricConfiguration
  fullName: Microsoft.ApplicationInsights.Metrics.MetricConfiguration
- uid: Microsoft.ApplicationInsights.Metrics.MetricConfigurationForMeasurement
  commentId: T:Microsoft.ApplicationInsights.Metrics.MetricConfigurationForMeasurement
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.MetricConfigurationForMeasurement.html
  name: MetricConfigurationForMeasurement
  nameWithType: MetricConfigurationForMeasurement
  fullName: Microsoft.ApplicationInsights.Metrics.MetricConfigurationForMeasurement
- uid: Microsoft.ApplicationInsights.Metrics.MetricIdentifier
  commentId: T:Microsoft.ApplicationInsights.Metrics.MetricIdentifier
  parent: Microsoft.ApplicationInsights.Metrics
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.MetricIdentifier.html
  name: MetricIdentifier
  nameWithType: MetricIdentifier
  fullName: Microsoft.ApplicationInsights.Metrics.MetricIdentifier
- uid: Microsoft.ApplicationInsights.Metrics.MetricManager
  commentId: T:Microsoft.ApplicationInsights.Metrics.MetricManager
  parent: Microsoft.ApplicationInsights.Metrics
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.MetricManager.html
  name: MetricManager
  nameWithType: MetricManager
  fullName: Microsoft.ApplicationInsights.Metrics.MetricManager
- uid: Microsoft.ApplicationInsights.Metrics.MetricsCollection
  commentId: T:Microsoft.ApplicationInsights.Metrics.MetricsCollection
  parent: Microsoft.ApplicationInsights.Metrics
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.MetricsCollection.html
  name: MetricsCollection
  nameWithType: MetricsCollection
  fullName: Microsoft.ApplicationInsights.Metrics.MetricsCollection
- uid: Microsoft.ApplicationInsights.Metrics.MetricSeries
  commentId: T:Microsoft.ApplicationInsights.Metrics.MetricSeries
  parent: Microsoft.ApplicationInsights.Metrics
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.MetricSeries.html
  name: MetricSeries
  nameWithType: MetricSeries
  fullName: Microsoft.ApplicationInsights.Metrics.MetricSeries
- uid: Microsoft.ApplicationInsights.Metrics.MetricSeriesConfigurationForMeasurement
  commentId: T:Microsoft.ApplicationInsights.Metrics.MetricSeriesConfigurationForMeasurement
  parent: Microsoft.ApplicationInsights.Metrics
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.MetricSeriesConfigurationForMeasurement.html
  name: MetricSeriesConfigurationForMeasurement
  nameWithType: MetricSeriesConfigurationForMeasurement
  fullName: Microsoft.ApplicationInsights.Metrics.MetricSeriesConfigurationForMeasurement
- uid: Microsoft.ApplicationInsights.Metrics.TelemetryConfigurationExtensions
  commentId: T:Microsoft.ApplicationInsights.Metrics.TelemetryConfigurationExtensions
  parent: Microsoft.ApplicationInsights.Metrics
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.TelemetryConfigurationExtensions.html
  name: TelemetryConfigurationExtensions
  nameWithType: TelemetryConfigurationExtensions
  fullName: Microsoft.ApplicationInsights.Metrics.TelemetryConfigurationExtensions
- uid: Microsoft.ApplicationInsights.Metrics
  commentId: N:Microsoft.ApplicationInsights.Metrics
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Metrics
  nameWithType: Microsoft.ApplicationInsights.Metrics
  fullName: Microsoft.ApplicationInsights.Metrics
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics
    name: Metrics
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics
    name: Metrics
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.html
