### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.ITestExecutionEnvironmentSpecifier
  commentId: T:Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.ITestExecutionEnvironmentSpecifier
  id: ITestExecutionEnvironmentSpecifier
  parent: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection
  children:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.ITestExecutionEnvironmentSpecifier.GetTestExecutionEnvironmentVariables
  langs:
  - csharp
  - vb
  name: ITestExecutionEnvironmentSpecifier
  nameWithType: ITestExecutionEnvironmentSpecifier
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.ITestExecutionEnvironmentSpecifier
  type: Interface
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel
  namespace: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection
  syntax:
    content: public interface ITestExecutionEnvironmentSpecifier
    content.vb: Public Interface ITestExecutionEnvironmentSpecifier
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.ITestExecutionEnvironmentSpecifier.GetTestExecutionEnvironmentVariables
  commentId: M:Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.ITestExecutionEnvironmentSpecifier.GetTestExecutionEnvironmentVariables
  id: GetTestExecutionEnvironmentVariables
  parent: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.ITestExecutionEnvironmentSpecifier
  langs:
  - csharp
  - vb
  name: GetTestExecutionEnvironmentVariables()
  nameWithType: ITestExecutionEnvironmentSpecifier.GetTestExecutionEnvironmentVariables()
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.ITestExecutionEnvironmentSpecifier.GetTestExecutionEnvironmentVariables()
  type: Method
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel
  namespace: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection
  syntax:
    content: IEnumerable<KeyValuePair<string, string>> GetTestExecutionEnvironmentVariables()
    return:
      type: System.Collections.Generic.IEnumerable{System.Collections.Generic.KeyValuePair{System.String,System.String}}
    content.vb: Function GetTestExecutionEnvironmentVariables() As IEnumerable(Of KeyValuePair(Of String, String))
  overload: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.ITestExecutionEnvironmentSpecifier.GetTestExecutionEnvironmentVariables*
references:
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection
  commentId: N:Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection
  isExternal: true
  href: Microsoft.html
  name: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection
  nameWithType: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel
    name: ObjectModel
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection
    name: DataCollection
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel
    name: ObjectModel
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection
    name: DataCollection
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.html
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.ITestExecutionEnvironmentSpecifier.GetTestExecutionEnvironmentVariables*
  commentId: Overload:Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.ITestExecutionEnvironmentSpecifier.GetTestExecutionEnvironmentVariables
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.ITestExecutionEnvironmentSpecifier.html#Microsoft_VisualStudio_TestPlatform_ObjectModel_DataCollection_ITestExecutionEnvironmentSpecifier_GetTestExecutionEnvironmentVariables
  name: GetTestExecutionEnvironmentVariables
  nameWithType: ITestExecutionEnvironmentSpecifier.GetTestExecutionEnvironmentVariables
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.ITestExecutionEnvironmentSpecifier.GetTestExecutionEnvironmentVariables
- uid: System.Collections.Generic.IEnumerable{System.Collections.Generic.KeyValuePair{System.String,System.String}}
  commentId: T:System.Collections.Generic.IEnumerable{System.Collections.Generic.KeyValuePair{System.String,System.String}}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<KeyValuePair<string, string>>
  nameWithType: IEnumerable<KeyValuePair<string, string>>
  fullName: System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, string>>
  nameWithType.vb: IEnumerable(Of KeyValuePair(Of String, String))
  fullName.vb: System.Collections.Generic.IEnumerable(Of System.Collections.Generic.KeyValuePair(Of String, String))
  name.vb: IEnumerable(Of KeyValuePair(Of String, String))
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - uid: System.Collections.Generic.KeyValuePair`2
    name: KeyValuePair
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.keyvaluepair-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Collections.Generic.KeyValuePair`2
    name: KeyValuePair
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.keyvaluepair-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
  - name: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
