### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider
  commentId: T:Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider
  id: ISettingsProvider
  parent: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  children:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.Load(System.Xml.XmlReader)
  langs:
  - csharp
  - vb
  name: ISettingsProvider
  nameWithType: ISettingsProvider
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider
  type: Interface
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel
  namespace: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  syntax:
    content: public interface ISettingsProvider
    content.vb: Public Interface ISettingsProvider
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.Load(System.Xml.XmlReader)
  commentId: M:Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.Load(System.Xml.XmlReader)
  id: Load(System.Xml.XmlReader)
  parent: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider
  langs:
  - csharp
  - vb
  name: Load(XmlReader)
  nameWithType: ISettingsProvider.Load(XmlReader)
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.Load(System.Xml.XmlReader)
  type: Method
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel
  namespace: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  syntax:
    content: void Load(XmlReader reader)
    parameters:
    - id: reader
      type: System.Xml.XmlReader
    content.vb: Sub Load(reader As XmlReader)
  overload: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.Load*
references:
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  commentId: N:Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  isExternal: true
  href: Microsoft.html
  name: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  nameWithType: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel
    name: ObjectModel
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
    name: Adapter
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel
    name: ObjectModel
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter
    name: Adapter
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.html
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.Load*
  commentId: Overload:Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.Load
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.html#Microsoft_VisualStudio_TestPlatform_ObjectModel_Adapter_ISettingsProvider_Load_System_Xml_XmlReader_
  name: Load
  nameWithType: ISettingsProvider.Load
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ISettingsProvider.Load
- uid: System.Xml.XmlReader
  commentId: T:System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Xml
  commentId: N:System.Xml
  isExternal: true
  name: System.Xml
  nameWithType: System.Xml
  fullName: System.Xml
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
  - name: .
  - uid: System.Xml
    name: Xml
    isExternal: true
  spec.vb:
  - uid: System
    name: System
    isExternal: true
  - name: .
  - uid: System.Xml
    name: Xml
    isExternal: true
