### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  commentId: T:Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  id: ITelemetryInitializer
  parent: Microsoft.ApplicationInsights.Extensibility
  children:
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  langs:
  - csharp
  - vb
  name: ITelemetryInitializer
  nameWithType: ITelemetryInitializer
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  type: Interface
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  syntax:
    content: public interface ITelemetryInitializer
    content.vb: Public Interface ITelemetryInitializer
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  id: Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  parent: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  langs:
  - csharp
  - vb
  name: Initialize(ITelemetry)
  nameWithType: ITelemetryInitializer.Initialize(ITelemetry)
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  type: Method
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  syntax:
    content: void Initialize(ITelemetry telemetry)
    parameters:
    - id: telemetry
      type: Microsoft.ApplicationInsights.Channel.ITelemetry
    content.vb: Sub Initialize(telemetry As ITelemetry)
  overload: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize*
references:
- uid: Microsoft.ApplicationInsights.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.html#Microsoft_ApplicationInsights_Extensibility_ITelemetryInitializer_Initialize_Microsoft_ApplicationInsights_Channel_ITelemetry_
  name: Initialize
  nameWithType: ITelemetryInitializer.Initialize
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry
  commentId: T:Microsoft.ApplicationInsights.Channel.ITelemetry
  parent: Microsoft.ApplicationInsights.Channel
  isExternal: true
  href: Microsoft.ApplicationInsights.Channel.ITelemetry.html
  name: ITelemetry
  nameWithType: ITelemetry
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
- uid: Microsoft.ApplicationInsights.Channel
  commentId: N:Microsoft.ApplicationInsights.Channel
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Channel
  nameWithType: Microsoft.ApplicationInsights.Channel
  fullName: Microsoft.ApplicationInsights.Channel
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Channel
    name: Channel
    isExternal: true
    href: Microsoft.ApplicationInsights.Channel.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Channel
    name: Channel
    isExternal: true
    href: Microsoft.ApplicationInsights.Channel.html
