### YamlMime:ManagedReference
items:
- uid: Microsoft.Testing.Platform.Builder.ITestApplication
  commentId: T:Microsoft.Testing.Platform.Builder.ITestApplication
  id: ITestApplication
  parent: Microsoft.Testing.Platform.Builder
  children:
  - Microsoft.Testing.Platform.Builder.ITestApplication.RunAsync
  langs:
  - csharp
  - vb
  name: ITestApplication
  nameWithType: ITestApplication
  fullName: Microsoft.Testing.Platform.Builder.ITestApplication
  type: Interface
  assemblies:
  - Microsoft.Testing.Platform
  namespace: Microsoft.Testing.Platform.Builder
  syntax:
    content: 'public interface ITestApplication : IDisposable'
    content.vb: Public Interface ITestApplication Inherits IDisposable
  inheritedMembers:
  - System.IDisposable.Dispose
- uid: Microsoft.Testing.Platform.Builder.ITestApplication.RunAsync
  commentId: M:Microsoft.Testing.Platform.Builder.ITestApplication.RunAsync
  id: RunAsync
  parent: Microsoft.Testing.Platform.Builder.ITestApplication
  langs:
  - csharp
  - vb
  name: RunAsync()
  nameWithType: ITestApplication.RunAsync()
  fullName: Microsoft.Testing.Platform.Builder.ITestApplication.RunAsync()
  type: Method
  assemblies:
  - Microsoft.Testing.Platform
  namespace: Microsoft.Testing.Platform.Builder
  syntax:
    content: Task<int> RunAsync()
    return:
      type: System.Threading.Tasks.Task{System.Int32}
    content.vb: Function RunAsync() As Task(Of Integer)
  overload: Microsoft.Testing.Platform.Builder.ITestApplication.RunAsync*
references:
- uid: Microsoft.Testing.Platform.Builder
  commentId: N:Microsoft.Testing.Platform.Builder
  isExternal: true
  href: Microsoft.html
  name: Microsoft.Testing.Platform.Builder
  nameWithType: Microsoft.Testing.Platform.Builder
  fullName: Microsoft.Testing.Platform.Builder
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Testing
    name: Testing
    isExternal: true
    href: Microsoft.Testing.html
  - name: .
  - uid: Microsoft.Testing.Platform
    name: Platform
    isExternal: true
    href: Microsoft.Testing.Platform.html
  - name: .
  - uid: Microsoft.Testing.Platform.Builder
    name: Builder
    isExternal: true
    href: Microsoft.Testing.Platform.Builder.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Testing
    name: Testing
    isExternal: true
    href: Microsoft.Testing.html
  - name: .
  - uid: Microsoft.Testing.Platform
    name: Platform
    isExternal: true
    href: Microsoft.Testing.Platform.html
  - name: .
  - uid: Microsoft.Testing.Platform.Builder
    name: Builder
    isExternal: true
    href: Microsoft.Testing.Platform.Builder.html
- uid: System.IDisposable.Dispose
  commentId: M:System.IDisposable.Dispose
  parent: System.IDisposable
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  name: Dispose()
  nameWithType: IDisposable.Dispose()
  fullName: System.IDisposable.Dispose()
  spec.csharp:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
  spec.vb:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
- uid: System.IDisposable
  commentId: T:System.IDisposable
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable
  name: IDisposable
  nameWithType: IDisposable
  fullName: System.IDisposable
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Testing.Platform.Builder.ITestApplication.RunAsync*
  commentId: Overload:Microsoft.Testing.Platform.Builder.ITestApplication.RunAsync
  isExternal: true
  href: Microsoft.Testing.Platform.Builder.ITestApplication.html#Microsoft_Testing_Platform_Builder_ITestApplication_RunAsync
  name: RunAsync
  nameWithType: ITestApplication.RunAsync
  fullName: Microsoft.Testing.Platform.Builder.ITestApplication.RunAsync
- uid: System.Threading.Tasks.Task{System.Int32}
  commentId: T:System.Threading.Tasks.Task{System.Int32}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<int>
  nameWithType: Task<int>
  fullName: System.Threading.Tasks.Task<int>
  nameWithType.vb: Task(Of Integer)
  fullName.vb: System.Threading.Tasks.Task(Of Integer)
  name.vb: Task(Of Integer)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
