### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.IExtension
  commentId: T:Microsoft.ApplicationInsights.Extensibility.IExtension
  id: IExtension
  parent: Microsoft.ApplicationInsights.Extensibility
  children:
  - Microsoft.ApplicationInsights.Extensibility.IExtension.DeepClone
  langs:
  - csharp
  - vb
  name: IExtension
  nameWithType: IExtension
  fullName: Microsoft.ApplicationInsights.Extensibility.IExtension
  type: Interface
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  syntax:
    content: 'public interface IExtension : ISerializableWithWriter'
    content.vb: Public Interface IExtension Inherits ISerializableWithWriter
  inheritedMembers:
  - Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.Serialize(Microsoft.ApplicationInsights.Extensibility.ISerializationWriter)
- uid: Microsoft.ApplicationInsights.Extensibility.IExtension.DeepClone
  commentId: M:Microsoft.ApplicationInsights.Extensibility.IExtension.DeepClone
  id: DeepClone
  parent: Microsoft.ApplicationInsights.Extensibility.IExtension
  langs:
  - csharp
  - vb
  name: DeepClone()
  nameWithType: IExtension.DeepClone()
  fullName: Microsoft.ApplicationInsights.Extensibility.IExtension.DeepClone()
  type: Method
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  syntax:
    content: IExtension DeepClone()
    return:
      type: Microsoft.ApplicationInsights.Extensibility.IExtension
    content.vb: Function DeepClone() As IExtension
  overload: Microsoft.ApplicationInsights.Extensibility.IExtension.DeepClone*
references:
- uid: Microsoft.ApplicationInsights.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
- uid: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.Serialize(Microsoft.ApplicationInsights.Extensibility.ISerializationWriter)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.Serialize(Microsoft.ApplicationInsights.Extensibility.ISerializationWriter)
  parent: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.html#Microsoft_ApplicationInsights_Extensibility_ISerializableWithWriter_Serialize_Microsoft_ApplicationInsights_Extensibility_ISerializationWriter_
  name: Serialize(ISerializationWriter)
  nameWithType: ISerializableWithWriter.Serialize(ISerializationWriter)
  fullName: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.Serialize(Microsoft.ApplicationInsights.Extensibility.ISerializationWriter)
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.Serialize(Microsoft.ApplicationInsights.Extensibility.ISerializationWriter)
    name: Serialize
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.html#Microsoft_ApplicationInsights_Extensibility_ISerializableWithWriter_Serialize_Microsoft_ApplicationInsights_Extensibility_ISerializationWriter_
  - name: (
  - uid: Microsoft.ApplicationInsights.Extensibility.ISerializationWriter
    name: ISerializationWriter
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.ISerializationWriter.html
  - name: )
  spec.vb:
  - uid: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.Serialize(Microsoft.ApplicationInsights.Extensibility.ISerializationWriter)
    name: Serialize
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.html#Microsoft_ApplicationInsights_Extensibility_ISerializableWithWriter_Serialize_Microsoft_ApplicationInsights_Extensibility_ISerializationWriter_
  - name: (
  - uid: Microsoft.ApplicationInsights.Extensibility.ISerializationWriter
    name: ISerializationWriter
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.ISerializationWriter.html
  - name: )
- uid: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter
  commentId: T:Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.html
  name: ISerializableWithWriter
  nameWithType: ISerializableWithWriter
  fullName: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter
- uid: Microsoft.ApplicationInsights.Extensibility.IExtension.DeepClone*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.IExtension.DeepClone
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.IExtension.html#Microsoft_ApplicationInsights_Extensibility_IExtension_DeepClone
  name: DeepClone
  nameWithType: IExtension.DeepClone
  fullName: Microsoft.ApplicationInsights.Extensibility.IExtension.DeepClone
- uid: Microsoft.ApplicationInsights.Extensibility.IExtension
  commentId: T:Microsoft.ApplicationInsights.Extensibility.IExtension
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.IExtension.html
  name: IExtension
  nameWithType: IExtension
  fullName: Microsoft.ApplicationInsights.Extensibility.IExtension
