### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  commentId: N:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  id: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
  - Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.FileDiagnosticsTelemetryModule
  - Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.IHeartbeatPropertyManager
  langs:
  - csharp
  - vb
  name: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  nameWithType: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  type: Namespace
  assemblies:
  - Microsoft.ApplicationInsights
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.html
  name: DiagnosticsTelemetryModule
  nameWithType: DiagnosticsTelemetryModule
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.FileDiagnosticsTelemetryModule
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.FileDiagnosticsTelemetryModule
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.FileDiagnosticsTelemetryModule.html
  name: FileDiagnosticsTelemetryModule
  nameWithType: FileDiagnosticsTelemetryModule
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.FileDiagnosticsTelemetryModule
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.IHeartbeatPropertyManager
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.IHeartbeatPropertyManager
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.IHeartbeatPropertyManager.html
  name: IHeartbeatPropertyManager
  nameWithType: IHeartbeatPropertyManager
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.IHeartbeatPropertyManager
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  commentId: N:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  nameWithType: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility.Implementation
    name: Implementation
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.Implementation.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
    name: Tracing
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility.Implementation
    name: Implementation
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.Implementation.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
    name: Tracing
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.html
