### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer
  commentId: T:Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer
  id: SequencePropertyInitializer
  parent: Microsoft.ApplicationInsights.Extensibility
  children:
  - Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.#ctor
  - Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  langs:
  - csharp
  - vb
  name: SequencePropertyInitializer
  nameWithType: SequencePropertyInitializer
  fullName: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer
  type: Class
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  syntax:
    content: 'public sealed class SequencePropertyInitializer : ITelemetryInitializer'
    content.vb: Public NotInheritable Class SequencePropertyInitializer Implements ITelemetryInitializer
  inheritance:
  - System.Object
  implements:
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  inheritedMembers:
  - System.Object.GetType
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  id: Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  parent: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer
  langs:
  - csharp
  - vb
  name: Initialize(ITelemetry)
  nameWithType: SequencePropertyInitializer.Initialize(ITelemetry)
  fullName: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  type: Method
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  example: []
  syntax:
    content: public void Initialize(ITelemetry telemetry)
    parameters:
    - id: telemetry
      type: Microsoft.ApplicationInsights.Channel.ITelemetry
    content.vb: Public Sub Initialize(telemetry As ITelemetry)
  overload: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.Initialize*
  implements:
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
- uid: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.#ctor
  commentId: M:Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.#ctor
  id: '#ctor'
  parent: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer
  langs:
  - csharp
  - vb
  name: SequencePropertyInitializer()
  nameWithType: SequencePropertyInitializer.SequencePropertyInitializer()
  fullName: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.SequencePropertyInitializer()
  type: Constructor
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  syntax:
    content: public SequencePropertyInitializer()
    content.vb: Public Sub New()
  overload: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.#ctor*
  nameWithType.vb: SequencePropertyInitializer.New()
  fullName.vb: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.New()
  name.vb: New()
references:
- uid: Microsoft.ApplicationInsights.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  commentId: T:Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.html
  name: ITelemetryInitializer
  nameWithType: ITelemetryInitializer
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.Initialize*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.Initialize
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.html#Microsoft_ApplicationInsights_Extensibility_SequencePropertyInitializer_Initialize_Microsoft_ApplicationInsights_Channel_ITelemetry_
  name: Initialize
  nameWithType: SequencePropertyInitializer.Initialize
  fullName: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.Initialize
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  parent: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.html#Microsoft_ApplicationInsights_Extensibility_ITelemetryInitializer_Initialize_Microsoft_ApplicationInsights_Channel_ITelemetry_
  name: Initialize(ITelemetry)
  nameWithType: ITelemetryInitializer.Initialize(ITelemetry)
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
    name: Initialize
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.html#Microsoft_ApplicationInsights_Extensibility_ITelemetryInitializer_Initialize_Microsoft_ApplicationInsights_Channel_ITelemetry_
  - name: (
  - uid: Microsoft.ApplicationInsights.Channel.ITelemetry
    name: ITelemetry
    isExternal: true
    href: Microsoft.ApplicationInsights.Channel.ITelemetry.html
  - name: )
  spec.vb:
  - uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
    name: Initialize
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.html#Microsoft_ApplicationInsights_Extensibility_ITelemetryInitializer_Initialize_Microsoft_ApplicationInsights_Channel_ITelemetry_
  - name: (
  - uid: Microsoft.ApplicationInsights.Channel.ITelemetry
    name: ITelemetry
    isExternal: true
    href: Microsoft.ApplicationInsights.Channel.ITelemetry.html
  - name: )
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry
  commentId: T:Microsoft.ApplicationInsights.Channel.ITelemetry
  parent: Microsoft.ApplicationInsights.Channel
  isExternal: true
  href: Microsoft.ApplicationInsights.Channel.ITelemetry.html
  name: ITelemetry
  nameWithType: ITelemetry
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
- uid: Microsoft.ApplicationInsights.Channel
  commentId: N:Microsoft.ApplicationInsights.Channel
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Channel
  nameWithType: Microsoft.ApplicationInsights.Channel
  fullName: Microsoft.ApplicationInsights.Channel
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Channel
    name: Channel
    isExternal: true
    href: Microsoft.ApplicationInsights.Channel.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Channel
    name: Channel
    isExternal: true
    href: Microsoft.ApplicationInsights.Channel.html
- uid: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.#ctor*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.#ctor
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.html#Microsoft_ApplicationInsights_Extensibility_SequencePropertyInitializer__ctor
  name: SequencePropertyInitializer
  nameWithType: SequencePropertyInitializer.SequencePropertyInitializer
  fullName: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.SequencePropertyInitializer
  nameWithType.vb: SequencePropertyInitializer.New
  fullName.vb: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.New
  name.vb: New
