### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.MetricAggregationScope
  commentId: T:Microsoft.ApplicationInsights.MetricAggregationScope
  id: MetricAggregationScope
  parent: Microsoft.ApplicationInsights
  children:
  - Microsoft.ApplicationInsights.MetricAggregationScope.TelemetryClient
  - Microsoft.ApplicationInsights.MetricAggregationScope.TelemetryConfiguration
  langs:
  - csharp
  - vb
  name: MetricAggregationScope
  nameWithType: MetricAggregationScope
  fullName: Microsoft.ApplicationInsights.MetricAggregationScope
  type: Enum
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  syntax:
    content: public enum MetricAggregationScope
    content.vb: Public Enum MetricAggregationScope
- uid: Microsoft.ApplicationInsights.MetricAggregationScope.TelemetryConfiguration
  commentId: F:Microsoft.ApplicationInsights.MetricAggregationScope.TelemetryConfiguration
  id: TelemetryConfiguration
  parent: Microsoft.ApplicationInsights.MetricAggregationScope
  langs:
  - csharp
  - vb
  name: TelemetryConfiguration
  nameWithType: MetricAggregationScope.TelemetryConfiguration
  fullName: Microsoft.ApplicationInsights.MetricAggregationScope.TelemetryConfiguration
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  syntax:
    content: TelemetryConfiguration = 0
    return:
      type: Microsoft.ApplicationInsights.MetricAggregationScope
- uid: Microsoft.ApplicationInsights.MetricAggregationScope.TelemetryClient
  commentId: F:Microsoft.ApplicationInsights.MetricAggregationScope.TelemetryClient
  id: TelemetryClient
  parent: Microsoft.ApplicationInsights.MetricAggregationScope
  langs:
  - csharp
  - vb
  name: TelemetryClient
  nameWithType: MetricAggregationScope.TelemetryClient
  fullName: Microsoft.ApplicationInsights.MetricAggregationScope.TelemetryClient
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  syntax:
    content: TelemetryClient = 1
    return:
      type: Microsoft.ApplicationInsights.MetricAggregationScope
references:
- uid: Microsoft.ApplicationInsights
  commentId: N:Microsoft.ApplicationInsights
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights
  nameWithType: Microsoft.ApplicationInsights
  fullName: Microsoft.ApplicationInsights
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
- uid: Microsoft.ApplicationInsights.MetricAggregationScope
  commentId: T:Microsoft.ApplicationInsights.MetricAggregationScope
  parent: Microsoft.ApplicationInsights
  isExternal: true
  href: Microsoft.ApplicationInsights.MetricAggregationScope.html
  name: MetricAggregationScope
  nameWithType: MetricAggregationScope
  fullName: Microsoft.ApplicationInsights.MetricAggregationScope
