### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule
  commentId: T:Microsoft.ApplicationInsights.Extensibility.ITelemetryModule
  id: ITelemetryModule
  parent: Microsoft.ApplicationInsights.Extensibility
  children:
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration)
  langs:
  - csharp
  - vb
  name: ITelemetryModule
  nameWithType: ITelemetryModule
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule
  type: Interface
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  syntax:
    content: public interface ITelemetryModule
    content.vb: Public Interface ITelemetryModule
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration)
  id: Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration)
  parent: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule
  langs:
  - csharp
  - vb
  name: Initialize(TelemetryConfiguration)
  nameWithType: ITelemetryModule.Initialize(TelemetryConfiguration)
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration)
  type: Method
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  syntax:
    content: void Initialize(TelemetryConfiguration configuration)
    parameters:
    - id: configuration
      type: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
    content.vb: Sub Initialize(configuration As TelemetryConfiguration)
  overload: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.Initialize*
references:
- uid: Microsoft.ApplicationInsights.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.Initialize*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.Initialize
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.html#Microsoft_ApplicationInsights_Extensibility_ITelemetryModule_Initialize_Microsoft_ApplicationInsights_Extensibility_TelemetryConfiguration_
  name: Initialize
  nameWithType: ITelemetryModule.Initialize
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.Initialize
- uid: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
  commentId: T:Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.html
  name: TelemetryConfiguration
  nameWithType: TelemetryConfiguration
  fullName: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
