### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration
  commentId: T:Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration
  id: ITestRunConfiguration
  parent: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client
  children:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.FrequencyOfRunStatsChangeEvent
  - Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.HasSpecificSources
  - Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.HasSpecificTests
  - Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.Tests
  langs:
  - csharp
  - vb
  name: ITestRunConfiguration
  nameWithType: ITestRunConfiguration
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration
  type: Interface
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel
  namespace: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client
  syntax:
    content: public interface ITestRunConfiguration
    content.vb: Public Interface ITestRunConfiguration
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.FrequencyOfRunStatsChangeEvent
  commentId: P:Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.FrequencyOfRunStatsChangeEvent
  id: FrequencyOfRunStatsChangeEvent
  parent: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration
  langs:
  - csharp
  - vb
  name: FrequencyOfRunStatsChangeEvent
  nameWithType: ITestRunConfiguration.FrequencyOfRunStatsChangeEvent
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.FrequencyOfRunStatsChangeEvent
  type: Property
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel
  namespace: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client
  syntax:
    content: long FrequencyOfRunStatsChangeEvent { get; }
    parameters: []
    return:
      type: System.Int64
    content.vb: ReadOnly Property FrequencyOfRunStatsChangeEvent As Long
  overload: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.FrequencyOfRunStatsChangeEvent*
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.HasSpecificTests
  commentId: P:Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.HasSpecificTests
  id: HasSpecificTests
  parent: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration
  langs:
  - csharp
  - vb
  name: HasSpecificTests
  nameWithType: ITestRunConfiguration.HasSpecificTests
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.HasSpecificTests
  type: Property
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel
  namespace: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client
  syntax:
    content: bool HasSpecificTests { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property HasSpecificTests As Boolean
  overload: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.HasSpecificTests*
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.HasSpecificSources
  commentId: P:Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.HasSpecificSources
  id: HasSpecificSources
  parent: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration
  langs:
  - csharp
  - vb
  name: HasSpecificSources
  nameWithType: ITestRunConfiguration.HasSpecificSources
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.HasSpecificSources
  type: Property
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel
  namespace: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client
  syntax:
    content: bool HasSpecificSources { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property HasSpecificSources As Boolean
  overload: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.HasSpecificSources*
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.Tests
  commentId: P:Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.Tests
  id: Tests
  parent: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration
  langs:
  - csharp
  - vb
  name: Tests
  nameWithType: ITestRunConfiguration.Tests
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.Tests
  type: Property
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.ObjectModel
  namespace: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client
  syntax:
    content: IEnumerable<TestCase>? Tests { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerable{Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase}
    content.vb: ReadOnly Property Tests As IEnumerable(Of TestCase)
  overload: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.Tests*
references:
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client
  commentId: N:Microsoft.VisualStudio.TestPlatform.ObjectModel.Client
  isExternal: true
  href: Microsoft.html
  name: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client
  nameWithType: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel
    name: ObjectModel
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client
    name: Client
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel
    name: ObjectModel
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client
    name: Client
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.html
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.FrequencyOfRunStatsChangeEvent*
  commentId: Overload:Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.FrequencyOfRunStatsChangeEvent
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.html#Microsoft_VisualStudio_TestPlatform_ObjectModel_Client_ITestRunConfiguration_FrequencyOfRunStatsChangeEvent
  name: FrequencyOfRunStatsChangeEvent
  nameWithType: ITestRunConfiguration.FrequencyOfRunStatsChangeEvent
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.FrequencyOfRunStatsChangeEvent
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int64
  name: long
  nameWithType: long
  fullName: long
  nameWithType.vb: Long
  fullName.vb: Long
  name.vb: Long
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.HasSpecificTests*
  commentId: Overload:Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.HasSpecificTests
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.html#Microsoft_VisualStudio_TestPlatform_ObjectModel_Client_ITestRunConfiguration_HasSpecificTests
  name: HasSpecificTests
  nameWithType: ITestRunConfiguration.HasSpecificTests
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.HasSpecificTests
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.HasSpecificSources*
  commentId: Overload:Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.HasSpecificSources
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.html#Microsoft_VisualStudio_TestPlatform_ObjectModel_Client_ITestRunConfiguration_HasSpecificSources
  name: HasSpecificSources
  nameWithType: ITestRunConfiguration.HasSpecificSources
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.HasSpecificSources
- uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.Tests*
  commentId: Overload:Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.Tests
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.html#Microsoft_VisualStudio_TestPlatform_ObjectModel_Client_ITestRunConfiguration_Tests
  name: Tests
  nameWithType: ITestRunConfiguration.Tests
  fullName: Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunConfiguration.Tests
- uid: System.Collections.Generic.IEnumerable{Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase}
  commentId: T:System.Collections.Generic.IEnumerable{Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<TestCase>
  nameWithType: IEnumerable<TestCase>
  fullName: System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase>
  nameWithType.vb: IEnumerable(Of TestCase)
  fullName.vb: System.Collections.Generic.IEnumerable(Of Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase)
  name.vb: IEnumerable(Of TestCase)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase
    name: TestCase
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - uid: Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase
    name: TestCase
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase.html
  - name: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
