### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline
  commentId: T:Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline
  id: IMetricTelemetryPipeline
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility
  children:
  - Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.FlushAsync(System.Threading.CancellationToken)
  - Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.TrackAsync(Microsoft.ApplicationInsights.Metrics.MetricAggregate,System.Threading.CancellationToken)
  langs:
  - csharp
  - vb
  name: IMetricTelemetryPipeline
  nameWithType: IMetricTelemetryPipeline
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline
  type: Interface
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Metrics.Extensibility
  syntax:
    content: public interface IMetricTelemetryPipeline
    content.vb: Public Interface IMetricTelemetryPipeline
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.TrackAsync(Microsoft.ApplicationInsights.Metrics.MetricAggregate,System.Threading.CancellationToken)
  commentId: M:Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.TrackAsync(Microsoft.ApplicationInsights.Metrics.MetricAggregate,System.Threading.CancellationToken)
  id: TrackAsync(Microsoft.ApplicationInsights.Metrics.MetricAggregate,System.Threading.CancellationToken)
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline
  langs:
  - csharp
  - vb
  name: TrackAsync(MetricAggregate, CancellationToken)
  nameWithType: IMetricTelemetryPipeline.TrackAsync(MetricAggregate, CancellationToken)
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.TrackAsync(Microsoft.ApplicationInsights.Metrics.MetricAggregate, System.Threading.CancellationToken)
  type: Method
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Metrics.Extensibility
  syntax:
    content: Task TrackAsync(MetricAggregate metricAggregate, CancellationToken cancelToken)
    parameters:
    - id: metricAggregate
      type: Microsoft.ApplicationInsights.Metrics.MetricAggregate
    - id: cancelToken
      type: System.Threading.CancellationToken
    return:
      type: System.Threading.Tasks.Task
    content.vb: Function TrackAsync(metricAggregate As MetricAggregate, cancelToken As CancellationToken) As Task
  overload: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.TrackAsync*
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.FlushAsync(System.Threading.CancellationToken)
  commentId: M:Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.FlushAsync(System.Threading.CancellationToken)
  id: FlushAsync(System.Threading.CancellationToken)
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline
  langs:
  - csharp
  - vb
  name: FlushAsync(CancellationToken)
  nameWithType: IMetricTelemetryPipeline.FlushAsync(CancellationToken)
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.FlushAsync(System.Threading.CancellationToken)
  type: Method
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Metrics.Extensibility
  syntax:
    content: Task FlushAsync(CancellationToken cancelToken)
    parameters:
    - id: cancelToken
      type: System.Threading.CancellationToken
    return:
      type: System.Threading.Tasks.Task
    content.vb: Function FlushAsync(cancelToken As CancellationToken) As Task
  overload: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.FlushAsync*
references:
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Metrics.Extensibility
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Metrics.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Metrics.Extensibility
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics
    name: Metrics
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.Extensibility.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics
    name: Metrics
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.Extensibility.html
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.TrackAsync*
  commentId: Overload:Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.TrackAsync
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.html#Microsoft_ApplicationInsights_Metrics_Extensibility_IMetricTelemetryPipeline_TrackAsync_Microsoft_ApplicationInsights_Metrics_MetricAggregate_System_Threading_CancellationToken_
  name: TrackAsync
  nameWithType: IMetricTelemetryPipeline.TrackAsync
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.TrackAsync
- uid: Microsoft.ApplicationInsights.Metrics.MetricAggregate
  commentId: T:Microsoft.ApplicationInsights.Metrics.MetricAggregate
  parent: Microsoft.ApplicationInsights.Metrics
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.MetricAggregate.html
  name: MetricAggregate
  nameWithType: MetricAggregate
  fullName: Microsoft.ApplicationInsights.Metrics.MetricAggregate
- uid: System.Threading.CancellationToken
  commentId: T:System.Threading.CancellationToken
  parent: System.Threading
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.cancellationtoken
  name: CancellationToken
  nameWithType: CancellationToken
  fullName: System.Threading.CancellationToken
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: Microsoft.ApplicationInsights.Metrics
  commentId: N:Microsoft.ApplicationInsights.Metrics
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Metrics
  nameWithType: Microsoft.ApplicationInsights.Metrics
  fullName: Microsoft.ApplicationInsights.Metrics
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics
    name: Metrics
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics
    name: Metrics
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.html
- uid: System.Threading
  commentId: N:System.Threading
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading
  nameWithType: System.Threading
  fullName: System.Threading
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.FlushAsync*
  commentId: Overload:Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.FlushAsync
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.html#Microsoft_ApplicationInsights_Metrics_Extensibility_IMetricTelemetryPipeline_FlushAsync_System_Threading_CancellationToken_
  name: FlushAsync
  nameWithType: IMetricTelemetryPipeline.FlushAsync
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.FlushAsync
