### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ISettingsProviderCapabilities
  commentId: T:Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ISettingsProviderCapabilities
  id: ISettingsProviderCapabilities
  parent: Microsoft.VisualStudio.TestPlatform.Common.Interfaces
  children:
  - Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ISettingsProviderCapabilities.SettingsName
  langs:
  - csharp
  - vb
  name: ISettingsProviderCapabilities
  nameWithType: ISettingsProviderCapabilities
  fullName: Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ISettingsProviderCapabilities
  type: Interface
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.Common
  namespace: Microsoft.VisualStudio.TestPlatform.Common.Interfaces
  syntax:
    content: public interface ISettingsProviderCapabilities
    content.vb: Public Interface ISettingsProviderCapabilities
- uid: Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ISettingsProviderCapabilities.SettingsName
  commentId: P:Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ISettingsProviderCapabilities.SettingsName
  id: SettingsName
  parent: Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ISettingsProviderCapabilities
  langs:
  - csharp
  - vb
  name: SettingsName
  nameWithType: ISettingsProviderCapabilities.SettingsName
  fullName: Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ISettingsProviderCapabilities.SettingsName
  type: Property
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.Common
  namespace: Microsoft.VisualStudio.TestPlatform.Common.Interfaces
  syntax:
    content: string SettingsName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property SettingsName As String
  overload: Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ISettingsProviderCapabilities.SettingsName*
references:
- uid: Microsoft.VisualStudio.TestPlatform.Common.Interfaces
  commentId: N:Microsoft.VisualStudio.TestPlatform.Common.Interfaces
  isExternal: true
  href: Microsoft.html
  name: Microsoft.VisualStudio.TestPlatform.Common.Interfaces
  nameWithType: Microsoft.VisualStudio.TestPlatform.Common.Interfaces
  fullName: Microsoft.VisualStudio.TestPlatform.Common.Interfaces
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.Common
    name: Common
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.Common.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.Common.Interfaces
    name: Interfaces
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.Common.Interfaces.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.Common
    name: Common
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.Common.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.Common.Interfaces
    name: Interfaces
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.Common.Interfaces.html
- uid: Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ISettingsProviderCapabilities.SettingsName*
  commentId: Overload:Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ISettingsProviderCapabilities.SettingsName
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ISettingsProviderCapabilities.html#Microsoft_VisualStudio_TestPlatform_Common_Interfaces_ISettingsProviderCapabilities_SettingsName
  name: SettingsName
  nameWithType: ISettingsProviderCapabilities.SettingsName
  fullName: Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ISettingsProviderCapabilities.SettingsName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
