### YamlMime:ManagedReference
items:
- uid: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask
  commentId: T:Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask
  id: ConfigurationFileTask
  parent: Microsoft.Testing.Platform.MSBuild
  children:
  - Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.#ctor
  - Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.AssemblyName
  - Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.Execute
  - Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.FinalTestingPlatformConfigurationFile
  - Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.MSBuildProjectDirectory
  - Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.OutputPath
  - Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.TestingPlatformConfigurationFileSource
  langs:
  - csharp
  - vb
  name: ConfigurationFileTask
  nameWithType: ConfigurationFileTask
  fullName: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask
  type: Class
  assemblies:
  - Microsoft.Testing.Platform.MSBuild
  namespace: Microsoft.Testing.Platform.MSBuild
  syntax:
    content: 'public sealed class ConfigurationFileTask : Task'
    content.vb: Public NotInheritable Class ConfigurationFileTask Inherits Task
  inheritance:
  - System.Object
- uid: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.#ctor
  commentId: M:Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.#ctor
  id: '#ctor'
  parent: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask
  langs:
  - csharp
  - vb
  name: ConfigurationFileTask()
  nameWithType: ConfigurationFileTask.ConfigurationFileTask()
  fullName: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.ConfigurationFileTask()
  type: Constructor
  assemblies:
  - Microsoft.Testing.Platform.MSBuild
  namespace: Microsoft.Testing.Platform.MSBuild
  syntax:
    content: public ConfigurationFileTask()
    content.vb: Public Sub New()
  overload: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.#ctor*
  nameWithType.vb: ConfigurationFileTask.New()
  fullName.vb: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.New()
  name.vb: New()
- uid: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.Execute
  commentId: M:Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.Execute
  id: Execute
  parent: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask
  langs:
  - csharp
  - vb
  name: Execute()
  nameWithType: ConfigurationFileTask.Execute()
  fullName: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.Execute()
  type: Method
  assemblies:
  - Microsoft.Testing.Platform.MSBuild
  namespace: Microsoft.Testing.Platform.MSBuild
  example: []
  syntax:
    content: public override bool Execute()
    return:
      type: System.Boolean
    content.vb: Public Overrides Function Execute() As Boolean
  overload: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.Execute*
- uid: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.TestingPlatformConfigurationFileSource
  commentId: P:Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.TestingPlatformConfigurationFileSource
  id: TestingPlatformConfigurationFileSource
  parent: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask
  langs:
  - csharp
  - vb
  name: TestingPlatformConfigurationFileSource
  nameWithType: ConfigurationFileTask.TestingPlatformConfigurationFileSource
  fullName: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.TestingPlatformConfigurationFileSource
  type: Property
  assemblies:
  - Microsoft.Testing.Platform.MSBuild
  namespace: Microsoft.Testing.Platform.MSBuild
  syntax:
    content: public ITaskItem TestingPlatformConfigurationFileSource { get; set; }
    parameters: []
    return:
      type: Microsoft.Build.Framework.ITaskItem
    content.vb: Public Property TestingPlatformConfigurationFileSource As ITaskItem
  overload: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.TestingPlatformConfigurationFileSource*
- uid: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.MSBuildProjectDirectory
  commentId: P:Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.MSBuildProjectDirectory
  id: MSBuildProjectDirectory
  parent: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask
  langs:
  - csharp
  - vb
  name: MSBuildProjectDirectory
  nameWithType: ConfigurationFileTask.MSBuildProjectDirectory
  fullName: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.MSBuildProjectDirectory
  type: Property
  assemblies:
  - Microsoft.Testing.Platform.MSBuild
  namespace: Microsoft.Testing.Platform.MSBuild
  syntax:
    content: public ITaskItem MSBuildProjectDirectory { get; set; }
    parameters: []
    return:
      type: Microsoft.Build.Framework.ITaskItem
    content.vb: Public Property MSBuildProjectDirectory As ITaskItem
  overload: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.MSBuildProjectDirectory*
- uid: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.AssemblyName
  commentId: P:Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.AssemblyName
  id: AssemblyName
  parent: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask
  langs:
  - csharp
  - vb
  name: AssemblyName
  nameWithType: ConfigurationFileTask.AssemblyName
  fullName: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.AssemblyName
  type: Property
  assemblies:
  - Microsoft.Testing.Platform.MSBuild
  namespace: Microsoft.Testing.Platform.MSBuild
  syntax:
    content: public ITaskItem AssemblyName { get; set; }
    parameters: []
    return:
      type: Microsoft.Build.Framework.ITaskItem
    content.vb: Public Property AssemblyName As ITaskItem
  overload: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.AssemblyName*
- uid: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.OutputPath
  commentId: P:Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.OutputPath
  id: OutputPath
  parent: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask
  langs:
  - csharp
  - vb
  name: OutputPath
  nameWithType: ConfigurationFileTask.OutputPath
  fullName: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.OutputPath
  type: Property
  assemblies:
  - Microsoft.Testing.Platform.MSBuild
  namespace: Microsoft.Testing.Platform.MSBuild
  syntax:
    content: public ITaskItem OutputPath { get; set; }
    parameters: []
    return:
      type: Microsoft.Build.Framework.ITaskItem
    content.vb: Public Property OutputPath As ITaskItem
  overload: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.OutputPath*
- uid: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.FinalTestingPlatformConfigurationFile
  commentId: P:Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.FinalTestingPlatformConfigurationFile
  id: FinalTestingPlatformConfigurationFile
  parent: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask
  langs:
  - csharp
  - vb
  name: FinalTestingPlatformConfigurationFile
  nameWithType: ConfigurationFileTask.FinalTestingPlatformConfigurationFile
  fullName: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.FinalTestingPlatformConfigurationFile
  type: Property
  assemblies:
  - Microsoft.Testing.Platform.MSBuild
  namespace: Microsoft.Testing.Platform.MSBuild
  syntax:
    content: public ITaskItem FinalTestingPlatformConfigurationFile { get; set; }
    parameters: []
    return:
      type: Microsoft.Build.Framework.ITaskItem
    content.vb: Public Property FinalTestingPlatformConfigurationFile As ITaskItem
  overload: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.FinalTestingPlatformConfigurationFile*
references:
- uid: Microsoft.Testing.Platform.MSBuild
  commentId: N:Microsoft.Testing.Platform.MSBuild
  isExternal: true
  href: Microsoft.html
  name: Microsoft.Testing.Platform.MSBuild
  nameWithType: Microsoft.Testing.Platform.MSBuild
  fullName: Microsoft.Testing.Platform.MSBuild
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Testing
    name: Testing
    isExternal: true
    href: Microsoft.Testing.html
  - name: .
  - uid: Microsoft.Testing.Platform
    name: Platform
    isExternal: true
    href: Microsoft.Testing.Platform.html
  - name: .
  - uid: Microsoft.Testing.Platform.MSBuild
    name: MSBuild
    isExternal: true
    href: Microsoft.Testing.Platform.MSBuild.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Testing
    name: Testing
    isExternal: true
    href: Microsoft.Testing.html
  - name: .
  - uid: Microsoft.Testing.Platform
    name: Platform
    isExternal: true
    href: Microsoft.Testing.Platform.html
  - name: .
  - uid: Microsoft.Testing.Platform.MSBuild
    name: MSBuild
    isExternal: true
    href: Microsoft.Testing.Platform.MSBuild.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.#ctor*
  commentId: Overload:Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.#ctor
  isExternal: true
  href: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.html#Microsoft_Testing_Platform_MSBuild_ConfigurationFileTask__ctor
  name: ConfigurationFileTask
  nameWithType: ConfigurationFileTask.ConfigurationFileTask
  fullName: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.ConfigurationFileTask
  nameWithType.vb: ConfigurationFileTask.New
  fullName.vb: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.New
  name.vb: New
- uid: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.Execute*
  commentId: Overload:Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.Execute
  isExternal: true
  href: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.html#Microsoft_Testing_Platform_MSBuild_ConfigurationFileTask_Execute
  name: Execute
  nameWithType: ConfigurationFileTask.Execute
  fullName: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.Execute
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.TestingPlatformConfigurationFileSource*
  commentId: Overload:Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.TestingPlatformConfigurationFileSource
  isExternal: true
  href: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.html#Microsoft_Testing_Platform_MSBuild_ConfigurationFileTask_TestingPlatformConfigurationFileSource
  name: TestingPlatformConfigurationFileSource
  nameWithType: ConfigurationFileTask.TestingPlatformConfigurationFileSource
  fullName: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.TestingPlatformConfigurationFileSource
- uid: Microsoft.Build.Framework.ITaskItem
  isExternal: true
  name: ITaskItem
  nameWithType: ITaskItem
  fullName: Microsoft.Build.Framework.ITaskItem
- uid: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.MSBuildProjectDirectory*
  commentId: Overload:Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.MSBuildProjectDirectory
  isExternal: true
  href: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.html#Microsoft_Testing_Platform_MSBuild_ConfigurationFileTask_MSBuildProjectDirectory
  name: MSBuildProjectDirectory
  nameWithType: ConfigurationFileTask.MSBuildProjectDirectory
  fullName: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.MSBuildProjectDirectory
- uid: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.AssemblyName*
  commentId: Overload:Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.AssemblyName
  isExternal: true
  href: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.html#Microsoft_Testing_Platform_MSBuild_ConfigurationFileTask_AssemblyName
  name: AssemblyName
  nameWithType: ConfigurationFileTask.AssemblyName
  fullName: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.AssemblyName
- uid: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.OutputPath*
  commentId: Overload:Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.OutputPath
  isExternal: true
  href: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.html#Microsoft_Testing_Platform_MSBuild_ConfigurationFileTask_OutputPath
  name: OutputPath
  nameWithType: ConfigurationFileTask.OutputPath
  fullName: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.OutputPath
- uid: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.FinalTestingPlatformConfigurationFile*
  commentId: Overload:Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.FinalTestingPlatformConfigurationFile
  isExternal: true
  href: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.html#Microsoft_Testing_Platform_MSBuild_ConfigurationFileTask_FinalTestingPlatformConfigurationFile
  name: FinalTestingPlatformConfigurationFile
  nameWithType: ConfigurationFileTask.FinalTestingPlatformConfigurationFile
  fullName: Microsoft.Testing.Platform.MSBuild.ConfigurationFileTask.FinalTestingPlatformConfigurationFile
