### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
  commentId: T:Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
  id: MetricAggregationCycleKind
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility
  children:
  - Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind.Custom
  - Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind.Default
  - Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind.QuickPulse
  langs:
  - csharp
  - vb
  name: MetricAggregationCycleKind
  nameWithType: MetricAggregationCycleKind
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
  type: Enum
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Metrics.Extensibility
  syntax:
    content: public enum MetricAggregationCycleKind
    content.vb: Public Enum MetricAggregationCycleKind
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind.Default
  commentId: F:Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind.Default
  id: Default
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
  langs:
  - csharp
  - vb
  name: Default
  nameWithType: MetricAggregationCycleKind.Default
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind.Default
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Metrics.Extensibility
  syntax:
    content: Default = 0
    return:
      type: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind.QuickPulse
  commentId: F:Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind.QuickPulse
  id: QuickPulse
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
  langs:
  - csharp
  - vb
  name: QuickPulse
  nameWithType: MetricAggregationCycleKind.QuickPulse
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind.QuickPulse
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Metrics.Extensibility
  syntax:
    content: QuickPulse = 1
    return:
      type: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind.Custom
  commentId: F:Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind.Custom
  id: Custom
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
  langs:
  - csharp
  - vb
  name: Custom
  nameWithType: MetricAggregationCycleKind.Custom
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind.Custom
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Metrics.Extensibility
  syntax:
    content: Custom = 2
    return:
      type: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
references:
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Metrics.Extensibility
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Metrics.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Metrics.Extensibility
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics
    name: Metrics
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.Extensibility.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics
    name: Metrics
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.Extensibility.html
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
  commentId: T:Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind.html
  name: MetricAggregationCycleKind
  nameWithType: MetricAggregationCycleKind
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
