### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment
  commentId: N:Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment
  id: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment
  children:
  - Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment.TestRunDirectories
  langs:
  - csharp
  - vb
  name: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment
  nameWithType: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment
  fullName: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment
  type: Namespace
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices
references:
- uid: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment.TestRunDirectories
  commentId: T:Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment.TestRunDirectories
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment.TestRunDirectories.html
  name: TestRunDirectories
  nameWithType: TestRunDirectories
  fullName: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment.TestRunDirectories
