### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter
  commentId: T:Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter
  id: ISerializableWithWriter
  parent: Microsoft.ApplicationInsights.Extensibility
  children:
  - Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.Serialize(Microsoft.ApplicationInsights.Extensibility.ISerializationWriter)
  langs:
  - csharp
  - vb
  name: ISerializableWithWriter
  nameWithType: ISerializableWithWriter
  fullName: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter
  type: Interface
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  syntax:
    content: public interface ISerializableWithWriter
    content.vb: Public Interface ISerializableWithWriter
- uid: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.Serialize(Microsoft.ApplicationInsights.Extensibility.ISerializationWriter)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.Serialize(Microsoft.ApplicationInsights.Extensibility.ISerializationWriter)
  id: Serialize(Microsoft.ApplicationInsights.Extensibility.ISerializationWriter)
  parent: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter
  langs:
  - csharp
  - vb
  name: Serialize(ISerializationWriter)
  nameWithType: ISerializableWithWriter.Serialize(ISerializationWriter)
  fullName: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.Serialize(Microsoft.ApplicationInsights.Extensibility.ISerializationWriter)
  type: Method
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  syntax:
    content: void Serialize(ISerializationWriter serializationWriter)
    parameters:
    - id: serializationWriter
      type: Microsoft.ApplicationInsights.Extensibility.ISerializationWriter
    content.vb: Sub Serialize(serializationWriter As ISerializationWriter)
  overload: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.Serialize*
references:
- uid: Microsoft.ApplicationInsights.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
- uid: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.Serialize*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.Serialize
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.html#Microsoft_ApplicationInsights_Extensibility_ISerializableWithWriter_Serialize_Microsoft_ApplicationInsights_Extensibility_ISerializationWriter_
  name: Serialize
  nameWithType: ISerializableWithWriter.Serialize
  fullName: Microsoft.ApplicationInsights.Extensibility.ISerializableWithWriter.Serialize
- uid: Microsoft.ApplicationInsights.Extensibility.ISerializationWriter
  commentId: T:Microsoft.ApplicationInsights.Extensibility.ISerializationWriter
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.ISerializationWriter.html
  name: ISerializationWriter
  nameWithType: ISerializationWriter
  fullName: Microsoft.ApplicationInsights.Extensibility.ISerializationWriter
