### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingDecision
  commentId: T:Microsoft.ApplicationInsights.DataContracts.SamplingDecision
  id: SamplingDecision
  parent: Microsoft.ApplicationInsights.DataContracts
  children:
  - Microsoft.ApplicationInsights.DataContracts.SamplingDecision.None
  - Microsoft.ApplicationInsights.DataContracts.SamplingDecision.SampledIn
  - Microsoft.ApplicationInsights.DataContracts.SamplingDecision.SampledOut
  langs:
  - csharp
  - vb
  name: SamplingDecision
  nameWithType: SamplingDecision
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingDecision
  type: Enum
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: public enum SamplingDecision
    content.vb: Public Enum SamplingDecision
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingDecision.None
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SamplingDecision.None
  id: None
  parent: Microsoft.ApplicationInsights.DataContracts.SamplingDecision
  langs:
  - csharp
  - vb
  name: None
  nameWithType: SamplingDecision.None
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingDecision.None
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: None = 0
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingDecision
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingDecision.SampledIn
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SamplingDecision.SampledIn
  id: SampledIn
  parent: Microsoft.ApplicationInsights.DataContracts.SamplingDecision
  langs:
  - csharp
  - vb
  name: SampledIn
  nameWithType: SamplingDecision.SampledIn
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingDecision.SampledIn
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: SampledIn = 1
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingDecision
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingDecision.SampledOut
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SamplingDecision.SampledOut
  id: SampledOut
  parent: Microsoft.ApplicationInsights.DataContracts.SamplingDecision
  langs:
  - csharp
  - vb
  name: SampledOut
  nameWithType: SamplingDecision.SampledOut
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingDecision.SampledOut
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: SampledOut = 2
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingDecision
references:
- uid: Microsoft.ApplicationInsights.DataContracts
  commentId: N:Microsoft.ApplicationInsights.DataContracts
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.DataContracts
  nameWithType: Microsoft.ApplicationInsights.DataContracts
  fullName: Microsoft.ApplicationInsights.DataContracts
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.DataContracts
    name: DataContracts
    isExternal: true
    href: Microsoft.ApplicationInsights.DataContracts.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.DataContracts
    name: DataContracts
    isExternal: true
    href: Microsoft.ApplicationInsights.DataContracts.html
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingDecision
  commentId: T:Microsoft.ApplicationInsights.DataContracts.SamplingDecision
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: true
  href: Microsoft.ApplicationInsights.DataContracts.SamplingDecision.html
  name: SamplingDecision
  nameWithType: SamplingDecision
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingDecision
