### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints
  commentId: N:Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints
  id: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints.EndpointContainer
  langs:
  - csharp
  - vb
  name: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints
  nameWithType: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints
  type: Namespace
  assemblies:
  - Microsoft.ApplicationInsights
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints.EndpointContainer
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints.EndpointContainer
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints.EndpointContainer.html
  name: EndpointContainer
  nameWithType: EndpointContainer
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints.EndpointContainer
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints
  commentId: N:Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints
  nameWithType: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility.Implementation
    name: Implementation
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.Implementation.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints
    name: Endpoints
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility.Implementation
    name: Implementation
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.Implementation.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints
    name: Endpoints
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints.html
