### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  commentId: T:Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  id: SamplingTelemetryItemTypes
  parent: Microsoft.ApplicationInsights.DataContracts
  children:
  - Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Availability
  - Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Event
  - Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Exception
  - Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Message
  - Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Metric
  - Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.None
  - Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.PageView
  - Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.PageViewPerformance
  - Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.PerformanceCounter
  - Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.RemoteDependency
  - Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Request
  - Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.SessionState
  langs:
  - csharp
  - vb
  name: SamplingTelemetryItemTypes
  nameWithType: SamplingTelemetryItemTypes
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  type: Enum
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: >-
      [Flags]

      public enum SamplingTelemetryItemTypes
    content.vb: >-
      <Flags>

      Public Enum SamplingTelemetryItemTypes
  attributes:
  - type: System.FlagsAttribute
    ctor: System.FlagsAttribute.#ctor
    arguments: []
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.None
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.None
  id: None
  parent: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  langs:
  - csharp
  - vb
  name: None
  nameWithType: SamplingTelemetryItemTypes.None
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.None
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: None = 0
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Event
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Event
  id: Event
  parent: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  langs:
  - csharp
  - vb
  name: Event
  nameWithType: SamplingTelemetryItemTypes.Event
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Event
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: Event = 1
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Exception
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Exception
  id: Exception
  parent: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  langs:
  - csharp
  - vb
  name: Exception
  nameWithType: SamplingTelemetryItemTypes.Exception
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Exception
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: Exception = 2
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Message
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Message
  id: Message
  parent: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  langs:
  - csharp
  - vb
  name: Message
  nameWithType: SamplingTelemetryItemTypes.Message
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Message
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: Message = 4
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Metric
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Metric
  id: Metric
  parent: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  langs:
  - csharp
  - vb
  name: Metric
  nameWithType: SamplingTelemetryItemTypes.Metric
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Metric
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: Metric = 8
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.PageView
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.PageView
  id: PageView
  parent: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  langs:
  - csharp
  - vb
  name: PageView
  nameWithType: SamplingTelemetryItemTypes.PageView
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.PageView
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: PageView = 16
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.PageViewPerformance
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.PageViewPerformance
  id: PageViewPerformance
  parent: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  langs:
  - csharp
  - vb
  name: PageViewPerformance
  nameWithType: SamplingTelemetryItemTypes.PageViewPerformance
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.PageViewPerformance
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: PageViewPerformance = 32
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.PerformanceCounter
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.PerformanceCounter
  id: PerformanceCounter
  parent: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  langs:
  - csharp
  - vb
  name: PerformanceCounter
  nameWithType: SamplingTelemetryItemTypes.PerformanceCounter
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.PerformanceCounter
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: PerformanceCounter = 64
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.RemoteDependency
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.RemoteDependency
  id: RemoteDependency
  parent: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  langs:
  - csharp
  - vb
  name: RemoteDependency
  nameWithType: SamplingTelemetryItemTypes.RemoteDependency
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.RemoteDependency
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: RemoteDependency = 128
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Request
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Request
  id: Request
  parent: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  langs:
  - csharp
  - vb
  name: Request
  nameWithType: SamplingTelemetryItemTypes.Request
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Request
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: Request = 256
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.SessionState
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.SessionState
  id: SessionState
  parent: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  langs:
  - csharp
  - vb
  name: SessionState
  nameWithType: SamplingTelemetryItemTypes.SessionState
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.SessionState
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: SessionState = 512
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Availability
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Availability
  id: Availability
  parent: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  langs:
  - csharp
  - vb
  name: Availability
  nameWithType: SamplingTelemetryItemTypes.Availability
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.Availability
  type: Field
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  syntax:
    content: Availability = 1024
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
references:
- uid: Microsoft.ApplicationInsights.DataContracts
  commentId: N:Microsoft.ApplicationInsights.DataContracts
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.DataContracts
  nameWithType: Microsoft.ApplicationInsights.DataContracts
  fullName: Microsoft.ApplicationInsights.DataContracts
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.DataContracts
    name: DataContracts
    isExternal: true
    href: Microsoft.ApplicationInsights.DataContracts.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.DataContracts
    name: DataContracts
    isExternal: true
    href: Microsoft.ApplicationInsights.DataContracts.html
- uid: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  commentId: T:Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: true
  href: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes.html
  name: SamplingTelemetryItemTypes
  nameWithType: SamplingTelemetryItemTypes
  fullName: Microsoft.ApplicationInsights.DataContracts.SamplingTelemetryItemTypes
