### YamlMime:ManagedReference
items:
- uid: Microsoft.Testing.Platform.Configurations
  commentId: N:Microsoft.Testing.Platform.Configurations
  id: Microsoft.Testing.Platform.Configurations
  children:
  - Microsoft.Testing.Platform.Configurations.ConfigurationExtensions
  - Microsoft.Testing.Platform.Configurations.IConfiguration
  langs:
  - csharp
  - vb
  name: Microsoft.Testing.Platform.Configurations
  nameWithType: Microsoft.Testing.Platform.Configurations
  fullName: Microsoft.Testing.Platform.Configurations
  type: Namespace
  assemblies:
  - Microsoft.Testing.Platform
references:
- uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions
  commentId: T:Microsoft.Testing.Platform.Configurations.ConfigurationExtensions
  parent: Microsoft.Testing.Platform.Configurations
  isExternal: true
  href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html
  name: ConfigurationExtensions
  nameWithType: ConfigurationExtensions
  fullName: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions
- uid: Microsoft.Testing.Platform.Configurations.IConfiguration
  commentId: T:Microsoft.Testing.Platform.Configurations.IConfiguration
  parent: Microsoft.Testing.Platform.Configurations
  isExternal: true
  href: Microsoft.Testing.Platform.Configurations.IConfiguration.html
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: Microsoft.Testing.Platform.Configurations.IConfiguration
- uid: Microsoft.Testing.Platform.Configurations
  commentId: N:Microsoft.Testing.Platform.Configurations
  isExternal: true
  href: Microsoft.html
  name: Microsoft.Testing.Platform.Configurations
  nameWithType: Microsoft.Testing.Platform.Configurations
  fullName: Microsoft.Testing.Platform.Configurations
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Testing
    name: Testing
    isExternal: true
    href: Microsoft.Testing.html
  - name: .
  - uid: Microsoft.Testing.Platform
    name: Platform
    isExternal: true
    href: Microsoft.Testing.Platform.html
  - name: .
  - uid: Microsoft.Testing.Platform.Configurations
    name: Configurations
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Testing
    name: Testing
    isExternal: true
    href: Microsoft.Testing.html
  - name: .
  - uid: Microsoft.Testing.Platform
    name: Platform
    isExternal: true
    href: Microsoft.Testing.Platform.html
  - name: .
  - uid: Microsoft.Testing.Platform.Configurations
    name: Configurations
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.html
