### YamlMime:ManagedReference
items:
- uid: Microsoft.Testing.Platform.Configurations.IConfiguration
  commentId: T:Microsoft.Testing.Platform.Configurations.IConfiguration
  id: IConfiguration
  parent: Microsoft.Testing.Platform.Configurations
  children:
  - Microsoft.Testing.Platform.Configurations.IConfiguration.Item(System.String)
  langs:
  - csharp
  - vb
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: Microsoft.Testing.Platform.Configurations.IConfiguration
  type: Interface
  assemblies:
  - Microsoft.Testing.Platform
  namespace: Microsoft.Testing.Platform.Configurations
  syntax:
    content: public interface IConfiguration
    content.vb: Public Interface IConfiguration
  extensionMethods:
  - Microsoft.Testing.Platform.Configurations.IConfiguration.Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetCurrentWorkingDirectory
  - Microsoft.Testing.Platform.Configurations.IConfiguration.Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestHostWorkingDirectory
  - Microsoft.Testing.Platform.Configurations.IConfiguration.Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestResultDirectory
- uid: Microsoft.Testing.Platform.Configurations.IConfiguration.Item(System.String)
  commentId: P:Microsoft.Testing.Platform.Configurations.IConfiguration.Item(System.String)
  id: Item(System.String)
  parent: Microsoft.Testing.Platform.Configurations.IConfiguration
  langs:
  - csharp
  - vb
  name: this[string]
  nameWithType: IConfiguration.this[string]
  fullName: Microsoft.Testing.Platform.Configurations.IConfiguration.this[string]
  type: Property
  assemblies:
  - Microsoft.Testing.Platform
  namespace: Microsoft.Testing.Platform.Configurations
  syntax:
    content: string? this[string key] { get; }
    parameters:
    - id: key
      type: System.String
    return:
      type: System.String
    content.vb: ReadOnly Default Property this[](key As String) As String
  overload: Microsoft.Testing.Platform.Configurations.IConfiguration.Item*
  nameWithType.vb: IConfiguration.this[](String)
  fullName.vb: Microsoft.Testing.Platform.Configurations.IConfiguration.this[](String)
  name.vb: this[](String)
references:
- uid: Microsoft.Testing.Platform.Configurations
  commentId: N:Microsoft.Testing.Platform.Configurations
  isExternal: true
  href: Microsoft.html
  name: Microsoft.Testing.Platform.Configurations
  nameWithType: Microsoft.Testing.Platform.Configurations
  fullName: Microsoft.Testing.Platform.Configurations
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Testing
    name: Testing
    isExternal: true
    href: Microsoft.Testing.html
  - name: .
  - uid: Microsoft.Testing.Platform
    name: Platform
    isExternal: true
    href: Microsoft.Testing.Platform.html
  - name: .
  - uid: Microsoft.Testing.Platform.Configurations
    name: Configurations
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Testing
    name: Testing
    isExternal: true
    href: Microsoft.Testing.html
  - name: .
  - uid: Microsoft.Testing.Platform
    name: Platform
    isExternal: true
    href: Microsoft.Testing.Platform.html
  - name: .
  - uid: Microsoft.Testing.Platform.Configurations
    name: Configurations
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.html
- uid: Microsoft.Testing.Platform.Configurations.IConfiguration.Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetCurrentWorkingDirectory
  commentId: M:Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetCurrentWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  parent: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions
  definition: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetCurrentWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetCurrentWorkingDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  name: GetCurrentWorkingDirectory(IConfiguration)
  nameWithType: ConfigurationExtensions.GetCurrentWorkingDirectory(IConfiguration)
  fullName: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetCurrentWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  spec.csharp:
  - uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetCurrentWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
    name: GetCurrentWorkingDirectory
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetCurrentWorkingDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  - name: (
  - uid: Microsoft.Testing.Platform.Configurations.IConfiguration
    name: IConfiguration
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.IConfiguration.html
  - name: )
  spec.vb:
  - uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetCurrentWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
    name: GetCurrentWorkingDirectory
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetCurrentWorkingDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  - name: (
  - uid: Microsoft.Testing.Platform.Configurations.IConfiguration
    name: IConfiguration
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.IConfiguration.html
  - name: )
- uid: Microsoft.Testing.Platform.Configurations.IConfiguration.Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestHostWorkingDirectory
  commentId: M:Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestHostWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  parent: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions
  definition: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestHostWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetTestHostWorkingDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  name: GetTestHostWorkingDirectory(IConfiguration)
  nameWithType: ConfigurationExtensions.GetTestHostWorkingDirectory(IConfiguration)
  fullName: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestHostWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  spec.csharp:
  - uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestHostWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
    name: GetTestHostWorkingDirectory
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetTestHostWorkingDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  - name: (
  - uid: Microsoft.Testing.Platform.Configurations.IConfiguration
    name: IConfiguration
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.IConfiguration.html
  - name: )
  spec.vb:
  - uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestHostWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
    name: GetTestHostWorkingDirectory
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetTestHostWorkingDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  - name: (
  - uid: Microsoft.Testing.Platform.Configurations.IConfiguration
    name: IConfiguration
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.IConfiguration.html
  - name: )
- uid: Microsoft.Testing.Platform.Configurations.IConfiguration.Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestResultDirectory
  commentId: M:Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestResultDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  parent: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions
  definition: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestResultDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetTestResultDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  name: GetTestResultDirectory(IConfiguration)
  nameWithType: ConfigurationExtensions.GetTestResultDirectory(IConfiguration)
  fullName: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestResultDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  spec.csharp:
  - uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestResultDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
    name: GetTestResultDirectory
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetTestResultDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  - name: (
  - uid: Microsoft.Testing.Platform.Configurations.IConfiguration
    name: IConfiguration
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.IConfiguration.html
  - name: )
  spec.vb:
  - uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestResultDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
    name: GetTestResultDirectory
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetTestResultDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  - name: (
  - uid: Microsoft.Testing.Platform.Configurations.IConfiguration
    name: IConfiguration
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.IConfiguration.html
  - name: )
- uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetCurrentWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  commentId: M:Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetCurrentWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  isExternal: true
  href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetCurrentWorkingDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  name: GetCurrentWorkingDirectory(IConfiguration)
  nameWithType: ConfigurationExtensions.GetCurrentWorkingDirectory(IConfiguration)
  fullName: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetCurrentWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  spec.csharp:
  - uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetCurrentWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
    name: GetCurrentWorkingDirectory
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetCurrentWorkingDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  - name: (
  - uid: Microsoft.Testing.Platform.Configurations.IConfiguration
    name: IConfiguration
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.IConfiguration.html
  - name: )
  spec.vb:
  - uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetCurrentWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
    name: GetCurrentWorkingDirectory
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetCurrentWorkingDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  - name: (
  - uid: Microsoft.Testing.Platform.Configurations.IConfiguration
    name: IConfiguration
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.IConfiguration.html
  - name: )
- uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions
  commentId: T:Microsoft.Testing.Platform.Configurations.ConfigurationExtensions
  parent: Microsoft.Testing.Platform.Configurations
  isExternal: true
  href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html
  name: ConfigurationExtensions
  nameWithType: ConfigurationExtensions
  fullName: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions
- uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestHostWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  commentId: M:Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestHostWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  isExternal: true
  href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetTestHostWorkingDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  name: GetTestHostWorkingDirectory(IConfiguration)
  nameWithType: ConfigurationExtensions.GetTestHostWorkingDirectory(IConfiguration)
  fullName: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestHostWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  spec.csharp:
  - uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestHostWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
    name: GetTestHostWorkingDirectory
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetTestHostWorkingDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  - name: (
  - uid: Microsoft.Testing.Platform.Configurations.IConfiguration
    name: IConfiguration
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.IConfiguration.html
  - name: )
  spec.vb:
  - uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestHostWorkingDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
    name: GetTestHostWorkingDirectory
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetTestHostWorkingDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  - name: (
  - uid: Microsoft.Testing.Platform.Configurations.IConfiguration
    name: IConfiguration
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.IConfiguration.html
  - name: )
- uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestResultDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  commentId: M:Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestResultDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  isExternal: true
  href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetTestResultDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  name: GetTestResultDirectory(IConfiguration)
  nameWithType: ConfigurationExtensions.GetTestResultDirectory(IConfiguration)
  fullName: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestResultDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
  spec.csharp:
  - uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestResultDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
    name: GetTestResultDirectory
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetTestResultDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  - name: (
  - uid: Microsoft.Testing.Platform.Configurations.IConfiguration
    name: IConfiguration
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.IConfiguration.html
  - name: )
  spec.vb:
  - uid: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.GetTestResultDirectory(Microsoft.Testing.Platform.Configurations.IConfiguration)
    name: GetTestResultDirectory
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.ConfigurationExtensions.html#Microsoft_Testing_Platform_Configurations_ConfigurationExtensions_GetTestResultDirectory_Microsoft_Testing_Platform_Configurations_IConfiguration_
  - name: (
  - uid: Microsoft.Testing.Platform.Configurations.IConfiguration
    name: IConfiguration
    isExternal: true
    href: Microsoft.Testing.Platform.Configurations.IConfiguration.html
  - name: )
- uid: Microsoft.Testing.Platform.Configurations.IConfiguration.Item*
  commentId: Overload:Microsoft.Testing.Platform.Configurations.IConfiguration.Item
  isExternal: true
  href: Microsoft.Testing.Platform.Configurations.IConfiguration.html#Microsoft_Testing_Platform_Configurations_IConfiguration_Item_System_String_
  name: this
  nameWithType: IConfiguration.this
  fullName: Microsoft.Testing.Platform.Configurations.IConfiguration.this
  nameWithType.vb: IConfiguration.this[]
  fullName.vb: Microsoft.Testing.Platform.Configurations.IConfiguration.this[]
  name.vb: this[]
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
