### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor
  commentId: T:Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor
  id: ITelemetryProcessor
  parent: Microsoft.ApplicationInsights.Extensibility
  children:
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.Process(Microsoft.ApplicationInsights.Channel.ITelemetry)
  langs:
  - csharp
  - vb
  name: ITelemetryProcessor
  nameWithType: ITelemetryProcessor
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor
  type: Interface
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  syntax:
    content: public interface ITelemetryProcessor
    content.vb: Public Interface ITelemetryProcessor
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.Process(Microsoft.ApplicationInsights.Channel.ITelemetry)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.Process(Microsoft.ApplicationInsights.Channel.ITelemetry)
  id: Process(Microsoft.ApplicationInsights.Channel.ITelemetry)
  parent: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor
  langs:
  - csharp
  - vb
  name: Process(ITelemetry)
  nameWithType: ITelemetryProcessor.Process(ITelemetry)
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.Process(Microsoft.ApplicationInsights.Channel.ITelemetry)
  type: Method
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  syntax:
    content: void Process(ITelemetry item)
    parameters:
    - id: item
      type: Microsoft.ApplicationInsights.Channel.ITelemetry
    content.vb: Sub Process(item As ITelemetry)
  overload: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.Process*
references:
- uid: Microsoft.ApplicationInsights.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Extensibility
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.Process*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.Process
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.html#Microsoft_ApplicationInsights_Extensibility_ITelemetryProcessor_Process_Microsoft_ApplicationInsights_Channel_ITelemetry_
  name: Process
  nameWithType: ITelemetryProcessor.Process
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.Process
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry
  commentId: T:Microsoft.ApplicationInsights.Channel.ITelemetry
  parent: Microsoft.ApplicationInsights.Channel
  isExternal: true
  href: Microsoft.ApplicationInsights.Channel.ITelemetry.html
  name: ITelemetry
  nameWithType: ITelemetry
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
- uid: Microsoft.ApplicationInsights.Channel
  commentId: N:Microsoft.ApplicationInsights.Channel
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Channel
  nameWithType: Microsoft.ApplicationInsights.Channel
  fullName: Microsoft.ApplicationInsights.Channel
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Channel
    name: Channel
    isExternal: true
    href: Microsoft.ApplicationInsights.Channel.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Channel
    name: Channel
    isExternal: true
    href: Microsoft.ApplicationInsights.Channel.html
