### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Metrics.Extensibility
  id: Microsoft.ApplicationInsights.Metrics.Extensibility
  children:
  - Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricSeriesAggregator
  - Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline
  - Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricValueFilter
  - Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
  - Microsoft.ApplicationInsights.Metrics.Extensibility.MetricExtensions
  - Microsoft.ApplicationInsights.Metrics.Extensibility.MetricSeriesExtensions
  - Microsoft.ApplicationInsights.Metrics.Extensibility.TelemetryClientExtensions
  langs:
  - csharp
  - vb
  name: Microsoft.ApplicationInsights.Metrics.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Metrics.Extensibility
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility
  type: Namespace
  assemblies:
  - Microsoft.ApplicationInsights
references:
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricSeriesAggregator
  commentId: T:Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricSeriesAggregator
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricSeriesAggregator.html
  name: IMetricSeriesAggregator
  nameWithType: IMetricSeriesAggregator
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricSeriesAggregator
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline
  commentId: T:Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline.html
  name: IMetricTelemetryPipeline
  nameWithType: IMetricTelemetryPipeline
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricTelemetryPipeline
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricValueFilter
  commentId: T:Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricValueFilter
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricValueFilter.html
  name: IMetricValueFilter
  nameWithType: IMetricValueFilter
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.IMetricValueFilter
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
  commentId: T:Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind.html
  name: MetricAggregationCycleKind
  nameWithType: MetricAggregationCycleKind
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricAggregationCycleKind
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricExtensions
  commentId: T:Microsoft.ApplicationInsights.Metrics.Extensibility.MetricExtensions
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricExtensions.html
  name: MetricExtensions
  nameWithType: MetricExtensions
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricExtensions
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricSeriesExtensions
  commentId: T:Microsoft.ApplicationInsights.Metrics.Extensibility.MetricSeriesExtensions
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricSeriesExtensions.html
  name: MetricSeriesExtensions
  nameWithType: MetricSeriesExtensions
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.MetricSeriesExtensions
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility.TelemetryClientExtensions
  commentId: T:Microsoft.ApplicationInsights.Metrics.Extensibility.TelemetryClientExtensions
  parent: Microsoft.ApplicationInsights.Metrics.Extensibility
  isExternal: true
  href: Microsoft.ApplicationInsights.Metrics.Extensibility.TelemetryClientExtensions.html
  name: TelemetryClientExtensions
  nameWithType: TelemetryClientExtensions
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility.TelemetryClientExtensions
- uid: Microsoft.ApplicationInsights.Metrics.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Metrics.Extensibility
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Metrics.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Metrics.Extensibility
  fullName: Microsoft.ApplicationInsights.Metrics.Extensibility
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics
    name: Metrics
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.Extensibility.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics
    name: Metrics
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Metrics.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Metrics.Extensibility.html
