### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider
  commentId: T:Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider
  id: ISettingsProvider
  parent: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface
  children:
  - Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.GetProperties(System.String)
  - Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.Load(System.Xml.XmlReader)
  langs:
  - csharp
  - vb
  name: ISettingsProvider
  nameWithType: ISettingsProvider
  fullName: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider
  type: Interface
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices
  namespace: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface
  syntax:
    content: public interface ISettingsProvider
    content.vb: Public Interface ISettingsProvider
- uid: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.Load(System.Xml.XmlReader)
  commentId: M:Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.Load(System.Xml.XmlReader)
  id: Load(System.Xml.XmlReader)
  parent: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider
  langs:
  - csharp
  - vb
  name: Load(XmlReader)
  nameWithType: ISettingsProvider.Load(XmlReader)
  fullName: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.Load(System.Xml.XmlReader)
  type: Method
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices
  namespace: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface
  syntax:
    content: void Load(XmlReader reader)
    parameters:
    - id: reader
      type: System.Xml.XmlReader
    content.vb: Sub Load(reader As XmlReader)
  overload: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.Load*
- uid: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.GetProperties(System.String)
  commentId: M:Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.GetProperties(System.String)
  id: GetProperties(System.String)
  parent: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider
  langs:
  - csharp
  - vb
  name: GetProperties(string)
  nameWithType: ISettingsProvider.GetProperties(string)
  fullName: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.GetProperties(string)
  type: Method
  assemblies:
  - Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices
  namespace: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface
  syntax:
    content: IDictionary<string, object> GetProperties(string source)
    parameters:
    - id: source
      type: System.String
    return:
      type: System.Collections.Generic.IDictionary{System.String,System.Object}
    content.vb: Function GetProperties(source As String) As IDictionary(Of String, Object)
  overload: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.GetProperties*
  nameWithType.vb: ISettingsProvider.GetProperties(String)
  fullName.vb: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.GetProperties(String)
  name.vb: GetProperties(String)
references:
- uid: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface
  commentId: N:Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface
  isExternal: true
  href: Microsoft.html
  name: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface
  nameWithType: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface
  fullName: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.MSTestAdapter
    name: MSTestAdapter
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices
    name: PlatformServices
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface
    name: Interface
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.VisualStudio
    name: VisualStudio
    isExternal: true
    href: Microsoft.VisualStudio.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform
    name: TestPlatform
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.MSTestAdapter
    name: MSTestAdapter
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices
    name: PlatformServices
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.html
  - name: .
  - uid: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface
    name: Interface
    isExternal: true
    href: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.html
- uid: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.Load*
  commentId: Overload:Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.Load
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.html#Microsoft_VisualStudio_TestPlatform_MSTestAdapter_PlatformServices_Interface_ISettingsProvider_Load_System_Xml_XmlReader_
  name: Load
  nameWithType: ISettingsProvider.Load
  fullName: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.Load
- uid: System.Xml.XmlReader
  commentId: T:System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Xml
  commentId: N:System.Xml
  isExternal: true
  name: System.Xml
  nameWithType: System.Xml
  fullName: System.Xml
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
  - name: .
  - uid: System.Xml
    name: Xml
    isExternal: true
  spec.vb:
  - uid: System
    name: System
    isExternal: true
  - name: .
  - uid: System.Xml
    name: Xml
    isExternal: true
- uid: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.GetProperties*
  commentId: Overload:Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.GetProperties
  isExternal: true
  href: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.html#Microsoft_VisualStudio_TestPlatform_MSTestAdapter_PlatformServices_Interface_ISettingsProvider_GetProperties_System_String_
  name: GetProperties
  nameWithType: ISettingsProvider.GetProperties
  fullName: Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.ISettingsProvider.GetProperties
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Collections.Generic.IDictionary{System.String,System.Object}
  commentId: T:System.Collections.Generic.IDictionary{System.String,System.Object}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IDictionary`2
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  name: IDictionary<string, object>
  nameWithType: IDictionary<string, object>
  fullName: System.Collections.Generic.IDictionary<string, object>
  nameWithType.vb: IDictionary(Of String, Object)
  fullName.vb: System.Collections.Generic.IDictionary(Of String, Object)
  name.vb: IDictionary(Of String, Object)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Collections.Generic.IDictionary`2
  commentId: T:System.Collections.Generic.IDictionary`2
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  name: IDictionary<TKey, TValue>
  nameWithType: IDictionary<TKey, TValue>
  fullName: System.Collections.Generic.IDictionary<TKey, TValue>
  nameWithType.vb: IDictionary(Of TKey, TValue)
  fullName.vb: System.Collections.Generic.IDictionary(Of TKey, TValue)
  name.vb: IDictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  - name: <
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  - name: (
  - name: Of
  - name: " "
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
