### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  id: OperationContext
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Id
  - Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Name
  - Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.ParentId
  - Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.SyntheticSource
  langs:
  - csharp
  - vb
  name: OperationContext
  nameWithType: OperationContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  type: Class
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  syntax:
    content: public sealed class OperationContext
    content.vb: Public NotInheritable Class OperationContext
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Id
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Id
  id: Id
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: OperationContext.Id
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Id
  type: Property
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  syntax:
    content: public string Id { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Id As String
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Id*
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.ParentId
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.ParentId
  id: ParentId
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  langs:
  - csharp
  - vb
  name: ParentId
  nameWithType: OperationContext.ParentId
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.ParentId
  type: Property
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  syntax:
    content: public string ParentId { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ParentId As String
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.ParentId*
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Name
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Name
  id: Name
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: OperationContext.Name
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Name
  type: Property
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  syntax:
    content: public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Name As String
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Name*
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.SyntheticSource
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.SyntheticSource
  id: SyntheticSource
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  langs:
  - csharp
  - vb
  name: SyntheticSource
  nameWithType: OperationContext.SyntheticSource
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.SyntheticSource
  type: Property
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  syntax:
    content: public string SyntheticSource { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SyntheticSource As String
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.SyntheticSource*
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation
  commentId: N:Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: true
  href: Microsoft.html
  name: Microsoft.ApplicationInsights.Extensibility.Implementation
  nameWithType: Microsoft.ApplicationInsights.Extensibility.Implementation
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility.Implementation
    name: Implementation
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.Implementation.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.ApplicationInsights
    name: ApplicationInsights
    isExternal: true
    href: Microsoft.ApplicationInsights.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility
    name: Extensibility
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.html
  - name: .
  - uid: Microsoft.ApplicationInsights.Extensibility.Implementation
    name: Implementation
    isExternal: true
    href: Microsoft.ApplicationInsights.Extensibility.Implementation.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Id*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Id
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.html#Microsoft_ApplicationInsights_Extensibility_Implementation_OperationContext_Id
  name: Id
  nameWithType: OperationContext.Id
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Id
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.ParentId*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.ParentId
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.html#Microsoft_ApplicationInsights_Extensibility_Implementation_OperationContext_ParentId
  name: ParentId
  nameWithType: OperationContext.ParentId
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.ParentId
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Name*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Name
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.html#Microsoft_ApplicationInsights_Extensibility_Implementation_OperationContext_Name
  name: Name
  nameWithType: OperationContext.Name
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Name
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.SyntheticSource*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.SyntheticSource
  isExternal: true
  href: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.html#Microsoft_ApplicationInsights_Extensibility_Implementation_OperationContext_SyntheticSource
  name: SyntheticSource
  nameWithType: OperationContext.SyntheticSource
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.SyntheticSource
